### ISSUE TITLE
Embedded checkout fails to load

### ISSUE THREAD

**Issue by byronwilliams** [bigcommerce/checkout-sdk-js#1000]
We are using BC4WP and are customizing the checkout process. When we enable the embedded checkout option in WP which uses a custom checkout (https://github.com/bigcommerce/checkout-sdk-js-example) a `NotEmbeddableError` is thrown. The same code loads fine when the checkout is not in embedded mode.

```
Uncaught (in promise) NotEmbeddableError: Unable to embed the iframe because the content could not be loaded.
    at https://checkout-sdk.bigcommerce.com/v1/embedded-checkout-35f78c66.js:47:24423
```

If you take a look at the following screenshot you can see that the DOM has rendered correctly inside the iframe.

![Screenshot from 2020-10-13 09-26-50](https://user-images.githubusercontent.com/303604/95835529-3e53b380-0d36-11eb-8060-b8c17faa6ed8.png)

It seems that message passing is not working between the `window`. 

Versions:

```
    "@bigcommerce/checkout-sdk": "^1.104.1",
```

**Comment by capsula4** [comment]
Hi Byron,

At the moment, customizing embedded checkout is not supported by BigCommerce. You could, however, customize the checkout and use a redirect instead of embedded checkout.

Greets,
Luis.

**Comment by le-dev-associate** [comment]
Hi @capsula4, I'm facing the same issue in our headless react+gatsby site. Is there any work around for this as we don't want to redirect the user to BC frontstore.

**Comment by byronwilliams** [comment]
@le-dev-associate - we have 2x Enterprise subscriptions with BC but have not had any luck convincing them it's a priority.  We have resorted to using the standard checkout with the redirect specified above - it works well but our conversion rate is slightly lower and you get a flash from the BC checkout page.

**Comment by skydev2020** [comment]
> Hi Byron,
> 
> At the moment, customizing embedded checkout is not supported by BigCommerce. You could, however, customize the checkout and use a redirect instead of embedded checkout.
> 
> Greets,
> Luis.

@capsula4  I think it is not a checkout customization, it is about to use embedded checkout url following this post
https://developer.bigcommerce.com/api-docs/storefronts/embedded-checkout/embedded-checkout-tutorial

I have same issue.
This is what happened.

1. I am using rails application locally.
    it is running as https://127.0.0.1:3000 (I've tried with localhost, but I can't create site using localhost: it says sitename should not contain localhost string)
  I created local ssl key and certification and runs the application by 
  rails s -b 'ssl://127.0.0.1:3000?key=127.0.0.1.key&cert=127.0.0.1.crt'
  
  And I can access the local site by  https://127.0.0.1:3000/ although it says 'Not Secure'
2. I followed the embedded checkout url and able to produce the redirect_urls
   for example:
   {
    "data": {
        "cart_url": "https://pbgtest.mybigcommerce.com/cart.php?action=load&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4",
        "checkout_url": "https://pbgtest.mybigcommerce.com/cart.php?action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4",
        "embedded_checkout_url": "https://pbgtest.mybigcommerce.com/cart.php?embedded=1&action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4"
    },
    "meta": {}
}
  whenever I copy checkout_url or embedded_checkout_url and paste it directly in addressbar it works fine.
  I also found that these urls should be at once not twice, so whenever I try a test I regenerate the url
3. In rails application, I added this code in one of page
  ```
<script src="https://checkout-sdk.bigcommerce.com/v1/loader.js"></script>
  <script>
    $(document).ready(function() {
      // const module = await checkoutKitLoader.load('embedded-checkout');
 
      async function show() {
        const module = await checkoutKitLoader.load('embedded-checkout');
        const service = module.embedCheckout({
          url: 'https://pbgtest.mybigcommerce.com/cart.php?embedded=1&action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4',
          containerId: 'embedded-checkout-section'  #This is  div id
        });
        service
        .then(value => {
          console.log(value);
          })
        .catch(err => {
            console.log(err);
          });
      }

      show();
   }
```
  But I get "NotEmbeddableError: Unable to embed the iframe because the content could not be loaded."
  I can't get the proper info like why it failed loading.
  I also tested after disable the Anti Virus software but still same error.
  Anybody can help?

**Comment by ersurajnegi** [comment]
Any updates on this, how to make embedded checkout work?

**Comment by skydev2020** [comment]
I don't think it has any update

**Comment by binkrassdufass** [comment]
> > Hi Byron,
> > At the moment, customizing embedded checkout is not supported by BigCommerce. You could, however, customize the checkout and use a redirect instead of embedded checkout.
> > Greets,
> > Luis.
> 
> @capsula4 I think it is not a checkout customization, it is about to use embedded checkout url following this post https://developer.bigcommerce.com/api-docs/storefronts/embedded-checkout/embedded-checkout-tutorial
> 
> I have same issue. This is what happened.
> 
>     1. I am using rails application locally.
>        it is running as https://127.0.0.1:3000 (I've tried with localhost, but I can't create site using localhost: it says sitename should not contain localhost string)
>        I created local ssl key and certification and runs the application by
>        rails s -b 'ssl://127.0.0.1:3000?key=127.0.0.1.key&cert=127.0.0.1.crt'
> 
> 
> And I can access the local site by https://127.0.0.1:3000/ although it says 'Not Secure' 2. I followed the embedded checkout url and able to produce the redirect_urls for example:
> 
> ```
> {
>  "data": {
>      "cart_url": "https://pbgtest.mybigcommerce.com/cart.php?action=load&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4",
>      "checkout_url": "https://pbgtest.mybigcommerce.com/cart.php?action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4",
>      "embedded_checkout_url": "https://pbgtest.mybigcommerce.com/cart.php?embedded=1&action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4"
>  },
>  "meta": {}
> }
> ```
> 
> whenever I copy checkout_url or embedded_checkout_url and paste it directly in addressbar it works fine. I also found that these urls should be at once not twice, so whenever I try a test I regenerate the url 3. In rails application, I added this code in one of page
> 
> ```
> <script src="https://checkout-sdk.bigcommerce.com/v1/loader.js"></script>
> <script>
>   $(document).ready(function() {
>     // const module = await checkoutKitLoader.load('embedded-checkout');
> 
>     async function show() {
>       const module = await checkoutKitLoader.load('embedded-checkout');
>       const service = module.embedCheckout({
>         url: 'https://pbgtest.mybigcommerce.com/cart.php?embedded=1&action=loadInCheckout&id=30df8201-90c9-4950-b784-0d35f16d2b63&token=10b5a5e6853217d23efdaf0b790b707dfd98fabde5495a5f2aaf7238fabbc5a4',
>         containerId: 'embedded-checkout-section'  #This is  div id
>       });
>       service
>       .then(value => {
>         console.log(value);
>         })
>       .catch(err => {
>           console.log(err);
>         });
>     }
> 
>     show();
>  }
> ```
> 
> But I get "NotEmbeddableError: Unable to embed the iframe because the content could not be loaded." I can't get the proper info like why it failed loading. I also tested after disable the Anti Virus software but still same error. Anybody can help?

exactly the same issue, any ideas how to fix it?
