### ISSUE TITLE
Square - Support Google Pay

### ISSUE THREAD

**Issue by rowleyaj** [bigcommerce/checkout-sdk-js#1033]
It would be great if we could support Google Pay for Square as they provide better rates in the UK than other payment providers that BigCommerce already support Google Pay for.

I've found the documentation for the square side but I'm unsure how to hook this up with the BigCommerce way of doing things in the SDK. Happy to attempt a PR if someone is able to point me in the right direction please.

https://developer.squareup.com/docs/payment-form/add-digital-wallets/google-pay

**Comment by bc-0dp** [comment]
@rowleyaj was this resolved?

**Comment by bc-0dp** [comment]
Closing this as our Square integration is deprecated
https://support.bigcommerce.com/s/article/Square-POS?language=en_US
