### ISSUE TITLE
Square - Support Masterpass

### ISSUE THREAD

**Issue by rowleyaj** [bigcommerce/checkout-sdk-js#1034]
It would be great if we could support Masterpass for Square as they provide better rates in the UK than other payment providers that BigCommerce already support Google Pay for.

I've found the documentation for the square side but I'm unsure how to hook this up with the BigCommerce way of doing things in the SDK.

Happy to attempt a PR if someone is able to point me in the right direction please.

https://developer.squareup.com/docs/payment-form/add-digital-wallets/masterpass

**Comment by bc-0dp** [comment]
https://support.bigcommerce.com/s/article/Square-POS?language=en_US
