### ISSUE TITLE
Square - Support Strong Customer Authentication

### ISSUE THREAD

**Issue by rowleyaj** [bigcommerce/checkout-sdk-js#1035]
> Strong Customer Authentication (SCA) is a new European regulation that went into effect on September 14, 2019, to make customer-initiated online and in-app payments more secure in the European Economic Area (EEA).
> 
> The FCA recently announced it is delaying the full enforcement of SCA by 18 months to March 2021, by which time all banks, retailers, and payment providers are expected to be fully prepared. Despite this enforcement delay, the FCA still expects payment providers to start rolling out new measures in a staggered approach from September 14, 2019.

See BigCommerce support case: 04563077

Square supports strong customer authentication but BigCommerce does not. We are already starting to see failed transactions where card providers are requiring SCA but BigCommerce does not support it.

https://developer.squareup.com/docs/sca-overview
https://developer.squareup.com/docs/payment-form/cookbook/verify-buyer-on-card-charge

**Comment by rowleyaj** [comment]
@capsula4 any chance you can point me in the right direction for docs on how to get started with fixing this?

I'm not getting any traction with support on getting this resolved and we're having more and more customers seeing unknown errors, which we believe is down to strong customer authentication not being supported. I'm happy to try and put a PR together but I'm not sure where to start.

**Comment by bc-0dp** [comment]
Closing this as our Sqaure integration is deprecated
https://support.bigcommerce.com/s/article/Square-POS?language=en_US

**Comment by rowleyaj** [comment]
@bc-0dp thanks for highlighting that deprecation for me as I wasn't aware! as a customer who actively uses the syncing between bigcommerce and square I'd expect some kind of notification so perhaps someone could inform customers please? is it only deprecated for new installs or existing customers too?

the link to the documentation only talks about the Square POS app being deprecated, not payments which this and the other closed issues are about - #1032 #1033 #1034. could you please share some clarity around this if you have it available.

**Comment by bc-0dp** [comment]
Hi @rowleyaj Let's reopen this and the other ones and get to the bottom of this!

**Comment by rowleyaj** [comment]
@bc-0dp no worries. it's probably worth checking which customers use the payment integration and which customers use the POS integration. I currently use the POS integration but not the payment integration.

The payment integration was poorly supported as Square just pushed it off to BigCommerce, and there was no appetite to fix the issue I identified. We stopped using Square for our online site as a result.

The POS integration is needed though, so we can sync our online inventory with our Square inventory. We have an occasional use Square Terminal that we use at craft fairs and it's important to not sell items at fairs that are sold on our website.

**Comment by bc-0dp** [comment]
Hi @rowleyaj 
The message I received in my end is that
> We've taking a little break from adding any new managed integrations for now. We plan to revisit this at the end of Q2.
With that being said, I have no influence on any decisions that will be made.

My recommendation would be to create an Idea over at https://support.bigcommerce.com/s/ideas?language=en_US

I'll let you decide if we should keep these issues open
🙏

**Comment by rowleyaj** [comment]
@bc-0dp unfortunately the ideas forum is basically were ideas go to languish. i'll close out the issue as BC don't have any intention of supporting the feature, and I don't use it as a payment gateway anymore, so don't feel the need to try and push for it.

**Comment by bc-0dp** [comment]
I apologize for that 😢

**Comment by rowleyaj** [comment]
not your fault :)
