### ISSUE TITLE
PaypalButtonInitializeOptions: Where to get clientId

### ISSUE THREAD

**Issue by fresh5447** [bigcommerce/checkout-sdk-js#1037]
Interface has a required property of [clientId](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/paypalbuttoninitializeoptions.md#clientid)

Though I am not sure what they are referencing with the "Client ID of the Paypal App."

The method I am using is "PayPal express", which I thought was just an automatic integration. 

Do I need to connect with Paypal Express Sandbox?

**Comment by bc-0dp** [comment]
@fresh5447 was this resolved?

**Comment by bc-0dp** [comment]
Closing this due to inactivty
