### ISSUE TITLE
Google Pay checkout button doesn't apply type and color from options

### ISSUE THREAD

**Issue by vinicius0026** [bigcommerce/checkout-sdk-js#1044]
Hi there!

I'm having an issue with the Google Pay button. It doesn't apply the provided `type` and `color`.

I'm calling `checkoutButtonInitializer.initializeButton` like so:

```typescript
checkoutButtonInitializer.initializeButton({
    methodId: "googlepaybraintree" as CheckoutButtonMethodType,
    containerId: "GooglePayButton",
    googlepaybraintree: {
    buttonType: 'long' as ButtonType
  }
});
```

But the generated button is the `short` version of GooglePay button.

The reason for that is that `GooglePayPaymentProcessor.createButton` is being called without the provided type and color. See https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts#L53

**Comment by cbandam** [comment]
This issue has been addressed in PR https://github.com/bigcommerce/checkout-sdk-js/pull/1141
