### ISSUE TITLE
How to generate the UI without being connected to a store

### ISSUE THREAD

**Issue by LaudersGate** [bigcommerce/checkout-sdk-js#1095]
#Background 

- This SDK cannot handle U.K. addresses BC says that state field is mandatory.
- Workaround - hide state field in CSS. 
- Obviously, this is not a long-term solution. 

**Goal** 
I need to branch off and fix the functions to work correctly. 

**Question***

- How to generate UI without being connected to the live store. 
- id like to avoid setting up a demo store (that's a workaround) 
- I'd like to provide a JSON input to mimic an order and have the checkout load 

**Summary**

I would like to know what is the most efficient way to generate the checkout UI from code while not being connected to a store.

**Comment by capsula4** [comment]
At the moment is not supported to generate a UI without having it connected to a store. The SDK relies on the APIs to operate.

I don't foresee it being something we would support as it's a foundation of how the SDK works.
