### ISSUE TITLE
Update documentation about paypalcommerce

### ISSUE THREAD

**Issue by okaysuper** [bigcommerce/checkout-sdk-js#1100]
**Problem**
I have been struggling for a while not being able to load paypalcommerce.
It seems that the documentation is either incorrect or outdated.

**Proposed solution**
I could make paypal work properly by initializing it this way:
` service.initializePayment({ paypalcommerce: {
                      clientId: 'YOUR_CLIENT_ID'
                      container: '#YOUR_CONTAINER_ID',
                      submitForm: () => {
                          this.submitOrder(
                              {
                                  payment: { methodId: 'paypalcommerce', }
                              }
                          );
                      },
                      onValidate: (resolve, reject) => {
                          const isValid = this.validatePaymentForm();
                          if (isValid) {
                              return resolve();
                          }
                          return reject();
                      },
                      onRenderButton: () => {
                           this.hidePaymentSubmitButton();
                      }
                  }})`

That might be helpful for other devs out there to add the following to the documentation:
- clientId property is required
- container needs a # to work, otherwise no element is found
- The callback functions within submitForm, onValidate, onRenderButton are just examples functions. These functions are currently not existing within the checkout SDK. (Here I mean submitOrder, validatePaymentForm and hidePaymentSubmitButton).  I would remove the reference to service during their declaration.

**Comment by capsula4** [comment]
Hi okaysuper,
I will notify the @bigcommerce/paypal team so they can take a look at your question.

**Comment by okaysuper** [comment]
Hello Luiz, thank you for that!

**Comment by anicache08** [comment]
Just want to ask if we have a sample validatePaymentForm function that we can use?

**Comment by vneutrino** [comment]
Hi @anicache08,
you can look into the [checkout-js](https://github.com/bigcommerce/checkout-js/blob/master/src/app/payment/paymentMethod/PaypalCommercePaymentMethod.tsx) for the examples, but it's a bit complex.
In simple terms `validatePaymentForm` it's a function that returns boolean value, depends if payment form is valid or not.

**Comment by anicache08** [comment]
Got it, will look into it. Thanks for the help!

**Comment by bc-0dp** [comment]
closing this as resolved. Do feel free to open a new issue if need be. ❤️
