### ISSUE TITLE
Any plans to support CORS?

### ISSUE THREAD

**Issue by spire-mike** [bigcommerce/checkout-sdk-js#1109]
Are there any plans for the storefront APIs and this SDK to support [CORS](https://github.com/bigcommerce/checkout-sdk-js#cors)?

We are building a new site using Nuxt and Vercel. It seems to be a pretty straight-forward process, but I was disappointed to discover the checkout sdk can not be used from our headless site's domain. Is this still true?

Are there any plans or timelines as to when the sdk will be usable from a headless site?

**Comment by capsula4** [comment]
There are no plans at the moment for supporting CORS.

However, one potential solution would be to create a custom checkout and use the embedded checkout option. This way, the embedded custom checkout would be loaded.

This option is not officially documented/supported but we have some merchants that have managed to get it working.

**Comment by spire-mike** [comment]
Thanks @capsula4 - from what I have read in your documentation, using the embedded checkout would also mean that certain payment providers like Amazon Pay would not be supported, is that right?
