### ISSUE TITLE
Error Initializing Klarnav2 Payment Method

### ISSUE THREAD

**Issue by fresh5447** [bigcommerce/checkout-sdk-js#1255]
When attempting to initialize the Klarnav2 payment method I receive the following error:

`unable to proceed because payment method data is unavailable or not properly configured.`

This is my current config:
```
                    await service.initializePayment({
                        methodId: 'pay_over_time',
                        gatewayId: 'klarnav2',
                        klarnav2: {
                            container: 'klarna-container',
                            onLoad: (e) => console.log('Klarna Loaded', e),
                            onError: (e) => console.error('Klarna Loaded Error', e)
                        },          
                    });
```
One thing that is odd is I expect this `methodId` to be `klarna`, but it is actually `pay_over_time`

![Screen Shot 2021-09-29 at 11 19 30 AM](https://user-images.githubusercontent.com/5817201/135339936-8fbaae50-c7a6-487b-9c90-a8d39aebe675.png)

[Here are the docs I am following](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/klarnav2paymentinitializeoptions.md), looks like everything should be straight forward, so I am not sure where I am going wrong.

Currently running:
`    "@bigcommerce/checkout-sdk": "^1.181.0",`

**Comment by bhargav-codes** [comment]
Did you find a solution to this issue ? I am facing the same problem with stripe
