### ISSUE TITLE
Empty Categories Array in Order Response

### ISSUE THREAD

**Issue by spire-phil** [bigcommerce/checkout-sdk-js#1392]
**Describe the bug**
When retrieving category information about items in an order, the result is an empty array even though the product is assigned a category

**To Reproduce**
1. Purchase a product that is associated with a category
2. Use the checkout SDK to retrieve the order. (Calling getOrder() on the instantiated checkout service in this case).
3. Console log the object looking at the categories field of  lineItems.physicalItems
4. The category field is an empty array.

**Expected behavior**
I expect the category data to be included in categories field instead of an empty array.

**Additional context**
Additionally, in the network tab, you can see that the call to /api/storefront/orders/{orderId} returns with the categories field as an empty array also.

**Comment by bc-mackxu** [comment]
Hey @spire-phil, the categories field is an optional field, the detail will return by adding parameter `include=lineItems.physicalItems.categories`. You may call loadOrder with additional parameter before calling getOrder.
Here is an example:
```
loadOrder(100, {params: {'include':['lineItems.physicalItems.categories']}});
```
More samples can be found in [here](https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/order/order-request-sender.spec.ts#L80-L94).

Please let me know if you have any question. 
Thank you

**Comment by spire-phil** [comment]
Thank you for this @bc-mackxu .  

I have it working with the example you shared.
