### ISSUE TITLE
Error with order.consignments in checkout

### ISSUE THREAD

**Issue by zachadams16** [bigcommerce/checkout-sdk-js#1547]
I am building a custom checkout confirmation page. I am seeing on the order object that OrderConsignments is in an array when the response it gets back from the api is not in an array. This allows me to not have access to order.consignments.shipping since it thinks orderConsignments should be an array. and order.consignments[0].shipping is undefined.

the order object looks like this where OrderConsignments is in an array:

`declare interface Order {
    baseAmount: number;
    billingAddress: BillingAddress;
    cartId: string;
    coupons: Coupon[];
    consignments: OrderConsignment[];
    currency: Currency;
    customerCanBeCreated: boolean;
    customerId: number;
    customerMessage: string;
    discountAmount: number;
    handlingCostTotal: number;
    hasDigitalItems: boolean;
    isComplete: boolean;
    isDownloadable: boolean;
    isTaxIncluded: boolean;
    lineItems: LineItemMap;
    orderAmount: number;
    orderAmountAsInteger: number;
    orderId: number;
    payments?: OrderPayments;
    giftWrappingCostTotal: number;
    shippingCostTotal: number;
    shippingCostBeforeDiscount: number;
    status: string;
    taxes: Tax[];
    taxTotal: number;
}
`
but the object we get back is like the one described [here ](https://developer.bigcommerce.com/api-reference/b3A6MjMxMzcyNA-get-order) where consignments is not in an array  so order.consignments[0] is undefined but order.consignments contains the shipping objects.

**Comment by animesh1987** [comment]
Hey @zachadams16 thanks for raising this issue. You are right about interface mismatch.

We have raised a PR to address this concern and should be resolved soon.

**Comment by zachadams16** [comment]
Thank you!

**Comment by animesh1987** [comment]
If you update your sdk version to latest i.e. `1.276.0`+ the interfaces should be fixed.
