### ISSUE TITLE
Copying Over consignments

### ISSUE THREAD

**Issue by zachadams16** [bigcommerce/checkout-sdk-js#1559]
I am building a custom cart which uses  the consignment API to build multiple ship tos. The problem is if I am signed in and I have consignments and I signed out. Then I build consignments and sign back in, it only will bring over the items in the cart and not the consignments from when I wasn't signed out. It works fine if there isn't anything in my logged in checkout. Is there a good way to send those consignments from my logged out user to there account when they login.  Something better than saving the consignments in local storage or something? If not all good just wanted to ask

**Comment by animesh1987** [comment]
Hey @zachadams16 yes this is by design once a customer logs out, we invalidate the consignments as the address will change for a logged in customer vs a guest, same for billing address as well. So will have to re-enter the address to create a new consignment. 

Hope this males sense.

**Comment by zachadams16** [comment]
Okay, thanks for the reply.
