### ISSUE TITLE
Amazon Pay backwards compatibility with 1.296.0 release

### ISSUE THREAD

**Issue by spire-mike** [bigcommerce/checkout-sdk-js#1630]
My current checkout uses version 1.115.0 of the SDK. I am suddenly seeing errors related to my Amazon Pay payment method. It seems the id of the payment method returned from the API has changed from `amazon` to `amazonpay`. Do you know when this changed? Did it have to do with the 1.296.0 release? Shouldn't there be some sort of backwards compatibility considered with a change like this or at least some sort of warning for developers?

<img width="675" alt="image" src="https://user-images.githubusercontent.com/77629408/194449354-8991d84d-4ca3-4983-a95b-027dfa4b4736.png">

This is causing errors in our custom checkout.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/77629408/194448981-bb2be231-0caf-4f1a-97ec-47d84cb14934.png">

**Comment by ggarcia-bc** [comment]
Hi @spire-mike, first, apologies for any inconvenience. We have taken a look into your issue and we noticed you have been impacted by the deprecation of the v1 of Amazon Pay in BigCommerce, you can notice you are under v1 when you get `amazon` as the payment method returned in the Checkout SDK. This means version 1.296.0 still contains the strategy to handle `amazon` (v1) but your Amazon Pay credentials have been upgraded so they are using now API v2.1 (`amazonpay`). Your Checkout SDK version 1.115.0 should be enough to support API v2.1 of Amazon Pay, however we strongly recommend you to get the latest Checkout SDK (1.296.0) which contains updates to support API v2.2.

**Comment by spire-mike** [comment]
Thank you for the information @ggarcia-bc. Attempting to upgrade to the latest sdk version has brought up two additional issues. I posted them here and am hoping you can help.

#1651 and #1652
