### ISSUE TITLE
Cannot find module '@bigcommerce/checkout-sdk/payment-integration-api' or its corresponding type declarations

### ISSUE THREAD

**Issue by bapord** [bigcommerce/checkout-sdk-js#1689]
**Describe the bug**
We are using the checkout-sdk package for our app, but when it is being compiled we get the following error:

Error: node_modules/@bigcommerce/checkout-sdk/dist/checkout-sdk.d.ts:2:32 - error TS2307: Cannot find module '@bigcommerce/checkout-sdk/payment-integration-api' or its corresponding type declarations.

2 import { Omit as Omit_2 } from '@bigcommerce/checkout-sdk/payment-integration-api';

**To Reproduce**
1. Create a typescript app
2. Install the sdk "npm i --save @bigcommerce/checkout-sdk"
3. Compile app

**Expected behavior**
I expect the app to compile without any issues, like it has on previous versions.  The current version I am seeing an issue is [1.308.0]

**Screenshots**
![Screenshot from 2022-11-15 15-14-41](https://user-images.githubusercontent.com/15984124/202016721-f449fa53-daf3-4a67-a2af-1d3e7085b5d8.png)

**Desktop (please complete the following information):**
N/A - the error doesn't show up in the browser

**Smartphone (please complete the following information):**
N/A - the error doesn't show up in the mobile browser

**Additional context**
We just recently updated the package version and this started happening.

**Comment by bc-peng** [comment]
Perhaps we can begin debugging by looking at your Node and NPM versions.

Can you also try version '1.306.0', which is the current version in `checkout-js` and has been built several times?

**Comment by bapord** [comment]
Node: 16.13.2
NPM: 8.1.2

1.306.0 gives the same error for me.  I was able to fix it by changing that line in the node modules from @bigcommerce/checkout-sdk/payment-integration-api to @bigcommerce/checkout-sdk

That's a temporary fix for me, but I should haven't to change any code in the node modules.
