### ISSUE TITLE
how to use a nextjs application to be able to capture the value of the product at checkout

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/checkout-sdk-js#1841]
To capture the value of the product in the cart in a BigCommerce store with an external API, do you need to follow these steps?

**Comment by animesh1987** [comment]
Hey @bernardojru can you please explain what you are trying to do. Also you mention following certain steps? Can you please explain the steps.

**Comment by bernardojru** [comment]
Want to create an application made with nextjs and install in the bigcommerce store. And this application should be able to pick up the total of the products that have been added to the cart. How do I use the application to pick up the total of products that the customer adds in the cart, remembering that it is an application made in nextjs that should work in bigcommerce?

**Comment by animesh1987** [comment]
This SDK only works on checkout page, or for wallet buttons on storefront. 

May I ask what is the purpose of the application? Is that a checkout offering you are building?

**Comment by bernardojru** [comment]
The app will only work on the checkout page.
 Yes it is a checkout offer!

**Comment by animesh1987** [comment]
Thanks for the reply, in that case you can look at this https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/Cart.md#lineitems as part of Cart. This is an object that has all the products in cart.

There can be four types of products that can be in cart https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/LineItemMap.md.

**Comment by bernardojru** [comment]
como é que isso pode me ajudar, por favor me explica passo a passo, não sei aonde começar???

**Comment by animesh1987** [comment]
First of all you need to have a cart when you come to checkout page. So you application if it's going to replace native checkout will be available at `/checkout` page. From there you can look into the state and retrieve the information. 

Do you have a store where you have this application installed?

**Comment by bernardojru** [comment]
I intend to create the app already with this functionality, and implement in my store already with this functionality

**Comment by animesh1987** [comment]
Yes, so for that to begin with you will need to have the app running on checkout page of your store. Since checkout page is only accessible if you have an active cart. 

And then if your app is running in checkout page, you can https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/checkout/checkout-service.ts#L193 use this to get a checkout with all properties.

**Comment by bernardojru** [comment]
From what I understand only possible to do this with the application already in the right store?
             
If yes how is I can add an app in the store being that it is in preliminary version?

**Comment by animesh1987** [comment]
I suppose that is something you might need to reach out to support for since there is a process involved in adding new apps. Also if you just want to get  `this application should be able to pick up the total of the products that have been added to the cart` this SDK seems to be not the right approach.

**Comment by bernardojru** [comment]
But is it possible to make this application?

**Comment by animesh1987** [comment]
Yes it is, but that seems like you can just call Cart API and get the information https://developer.bigcommerce.com/api-reference/eb3777c8094b0-get-a-cart.

**Comment by bernardojru** [comment]
ok, thank you so much for the attention!

**Comment by bernardojru** [comment]
I'm sorry one last thing, that last api you sent, asks for some data that I can not find can you show me where each dice is????
