### ISSUE TITLE
Add means of payment

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/checkout-sdk-js#1843]
Is it possible to add a new payment method in bigCommerce if yes, how?
How to add other means of payment in bigCommerce?

https://user-images.githubusercontent.com/93547947/219032072-28d24a38-9911-43fb-b363-62e6a6c6f8e7.png

**Comment by bc-0dp** [comment]
Hi @bernardojru I am closing this issue as it seems to be related to checkout customization rather than the SDK per see.
I can recommend that you join bigcommerce-devs.slack.com were dev's like yourself can assist with inquires like this ❤️
