### ISSUE TITLE
empty checkout

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/checkout-sdk-js#1875]
I want to take the checkout data with my api and my data https://api.bigcommerce.com/stores/j426dllqei/v3/carts/100 

The error that comes from the postman: {
    "status": 404,
    "type": "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes"
}

how to solve this problem? 😢

**Comment by animesh1987** [comment]
Hey @bernardojru have you created a cart already? Since don't think 100 is a cart number that we can have. Also feel these questions will be better answered in community slack channels.

**Comment by bernardojru** [comment]
could you send me the channels off the community?
