### ISSUE TITLE
new payment method

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/checkout-sdk-js#1876]
I wonder how do I add the new payment method at the bigcommerce checkout, what would be the steps to add?

**Comment by animesh1987** [comment]
Can you please explain what you mean by adding a payment method? You can enable payment methods via Bigcommerce control panel.

**Comment by bernardojru** [comment]
Add new payment methods used in africa, but specifically from another country, for users here to be able to buy on the bigcommerce website?
