### ISSUE TITLE
Error while consuming api

### ISSUE THREAD

**Issue by bernardojru** [bigcommerce/checkout-sdk-js#1880]
This is the code I used to get the api data:

async function fetchCartData() {
    try {
      const { data } = await axios.get(
        "https://api.bigcommerce.com/stores/j426dllqei/v3/carts/dd0001d4-c69c-48b5-b2a8-5c7d0402c8f4",
        {
          headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            Authorization: "dd0001d4-c69c-48b5-b2a8-5c7d0402c8f4",
          },
        }
      );
      setCartData(data);
      console.log(data);
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    fetchCartData();
  }, []);

I would like to have access to all the checkout data and when I use the api, it has always given this error down here:

GET https://api.bigcommerce.com/stores/j426dllqei/v3/carts/dd0001d4-c69c-48b5-b2a8-5c7d0402c8f4 net::ERR_FAILED

**Comment by bc-peng** [comment]
Can you follow this doc to get a cart's details?
https://developer.bigcommerce.com/api-reference/213ddc6deee1f-get-a-cart
