### ISSUE TITLE
Cart Data

### ISSUE THREAD

**Issue by Mpese-Joao** [bigcommerce/checkout-sdk-js#1885]
I want to kno if it is possible to access the cart data through the App?
I'm asking because i'm developing an app to read cart data. But whenever a press the button i get 401 error:

 const fetchBigCommerceData = async () => {
    try {
      const response = await fetch(
        "https://api.bigcommerce.com/stores/aherf0o3nw/v3/carts/{CartId}",
        {
          headers: {
           "Accept" : "application/json",
            "Content-Type" : "application/json",
            "X-Auth-Token" : "4*****************************,
            "X-Auth-Client" : "a*****************************",
          },
          mode: "no-cors",
        }
      );

**Comment by animesh1987** [comment]
Hey @Mpese-Joao this question is unrelated to SDK. But V3 endpoints are not supposed to be called from the browser hence the 401 I suppose. Feel free to reach out to be added to our slack dec community for help around this.
