### ISSUE TITLE
Custom payment Gateway Support

### ISSUE THREAD

**Issue by Kaushik-d44** [bigcommerce/checkout-sdk-js#2073]
Hi @all , 

I want to integrate a custom payment gateway for my store. 
Anyone have any code reference or documentation on how to implement it?

I want to Integrate Expinet Payment In Bigcommerce

Thanks In Advance

**Comment by animesh1987** [comment]
Hey @Kaushik-d44 just have a question, do the payments go via the BC infrastructure or some other infrastructure?

**Comment by nikunjhatkar** [comment]
@animesh1987 If possible then It will be BC infrastructure where from the admin manage enable/disable custom payment method.
![image](https://github.com/bigcommerce/checkout-sdk-js/assets/123067660/8aaca1a3-3064-4353-8c6a-23bd9c23f744)

If you have any other way then you can also suggest it.

**Comment by animesh1987** [comment]
just wanted to check will this provider be available in the the payment methods listed in control panel? I ask since the solution can be based on that information.

**Comment by nikunjhatkar** [comment]
No, It's not listed.

**Comment by animesh1987** [comment]
Yes I think that way you might need to build an app for integrating. I will ping folks from payments teams for advice as well.

cc @rabinshr do you have any insights into this? I doubt the provider can be integrated directly into checkout-SDK, if it's not integrated via our backend.

**Comment by Kaushik-d44** [comment]
Actually we want to Integrate Expinet Payment Gateway 

https://docs.expinet.net/developers/quick-start

it's Not Listed In Control Panel so Have To create custom

**Comment by animesh1987** [comment]
Yes right now we don't have a way to create such integrations via SDK, you might need to create your own app for that.

**Comment by nikunjhatkar** [comment]
Do you have any sample app code for this kind of things?

**Comment by animesh1987** [comment]
I am not aware of any, but I did find this https://support.bigcommerce.com/s/question/0D54O00006ttjrhSAA/add-custom-payment-gateway-on-the-checkout-page?language=en_US in support section feel free to refer to that. Closing this thread for now.
