### ISSUE TITLE
how to know any gift card applied on cart or not in bigcommerce ?

### ISSUE THREAD

**Issue by Kaushik-d44** [bigcommerce/checkout-sdk-js#2178]
@bc-peng  @animesh1987 @serhii-tkachenko 

Let assume I have Cart Which have 1 Product have 5 Qty. 
Applied Gift certificate 'Test23' successfully 

Now I checked Response Of API with GET methode 

URL : https://api.bigcommerce.com/stores/meiqejpw78/v3/carts/e6dd2966-43a3-40b0-a4fd-cc07ce2301f2

But In response i can not get gift certificate related data Like Giftcertificate applied or nor and Which Giftcaerificate applied 

I got API Response Like : 

{
    "data": {
        "id": "e6dd2966-43a3-40b0-a4fd-cc07ce2301f2",
        "customer_id": 12,
        "channel_id": 1,
        "email": "domadiyakd44@gmail.com",
        "currency": {
            "code": "USD"
        },
        "tax_included": false,
        "base_amount": 1000,
        "discount_amount": 0,
        "cart_amount": 1082.5,
        "coupons": [],
        "discounts": [
            {
                "id": "f4de4a4c-4aa2-45ed-86f4-1035e00d5ae1",
                "discounted_amount": 0
            }
        ],
        "line_items": {
            "physical_items": [
                {
                    "id": "f4de4a4c-4aa2-45ed-86f4-1035e00d5ae1",
                    "parent_id": null,
                    "variant_id": 345,
                    "product_id": 379,
                    "sku": "",
                    "name": "KD_Bigcommerce_20mm",
                    "url": "https://johnsgunstore.mybigcommerce.com/kd_bigcommerce_20mm/",
                    "quantity": 5,
                    "taxable": true,
                    "image_url": "https://cdn11.bigcommerce.com/s-meiqejpw78/products/379/images/435/285052_about-us__05021.1694423126.220.290.png?c=1",
                    "discounts": [],
                    "coupons": [],
                    "discount_amount": 0,
                    "coupon_amount": 0,
                    "original_price": 200,
                    "list_price": 200,
                    "sale_price": 200,
                    "extended_list_price": 1000,
                    "extended_sale_price": 1000,
                    "is_require_shipping": true,
                    "is_mutable": true
                }
            ],
            "digital_items": [],
            "gift_certificates": [],
            "custom_items": []
        },
        "created_time": "2023-09-11T12:26:45+00:00",
        "updated_time": "2023-09-12T09:24:15+00:00",
        "locale": "en"
    },
    "meta": {}
}

**Comment by animesh1987** [comment]
Hey @Kaushik-d44 don't think this query is related to checkout-sdk. For storefront APIs via SDK you can see we use this https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/coupon/gift-certificate-request-sender.ts#L19. You might need to find an equivalent example for v3.

**Comment by Kaushik-d44** [comment]
@animesh1987 

Thanks for support 

you are talking about 

https://yourstore.example.com/api/storefront/checkouts/{checkoutId}/gift-certificates -- Post method
In which we have to pass arguments like 
{
  "giftCertificateCode": "string"
}
and Out put Like Its will Add Giftcard To curent Checkout 


But My requirement is diffrent 
I want to check Any of Giftcards Applied On Cartpage Or Not ( true / false)
