### ISSUE TITLE
amazon-pay-v2-payment-processor.ts throwing (non-fatal) TypeError in the console when checkout containing Amazon Pay button is loaded 

### ISSUE THREAD

**Issue by MisterOctober** [bigcommerce/checkout-sdk-js#2310]
**Describe the bug**
When loading a checkout page that uses an Amazon Pay button, a nonfatal TypeError 
`this._amazonPayV2Button.onClick is not a function`
is thrown in the console, with file 
amazon-pay-v2-payment-processor.ts
being specified as the source of the error 

**To Reproduce**
1. in Chrome, load a BigCommerce store that uses `checkout-js` and has the Amazon Pay button enabled
2. Open the web console in Developer Tools
3. Navigate to the Checkout page

**Expected behavior**
The Checkout page with Amazon Pay button should load without throwing a console error.

**Desktop (please complete the following information):**
 - OS: MacOS and Fedora
 - Browser Chrome
 - Version 120.0.6099.71

**Additional context**
This error started appearing several weeks ago, 
the timing and the error source suggest it may be something to do with this commit (specifically, lns 76->83 of amazon-pay-v2-payment-processor.ts): 
https://github.com/bigcommerce/checkout-sdk-js/commit/2a4e0ec52b76cba5b5b4c0680778cfd8fff82164

**Comment by animesh1987** [comment]
Hey @MisterOctober thanks for raising this, we will have a look.

**Comment by animesh1987** [comment]
Thanks @vitalii-koshovyi for the quick resolution on this.

**Comment by MisterOctober** [comment]
Awesome, thanks fellas!
