### ISSUE TITLE
Add 3d secure iframe window size property to Braintree

### ISSUE THREAD

**Issue by twm-jamieb** [bigcommerce/checkout-sdk-js#2520]
**Is your feature request related to a problem? Please describe.**

The iframe presented by a 3D Secure challenge through Braintree defaults to 390x400 which is not optimal for all screen sizes

**Describe the solution you'd like**

The Braintree sdk has a "acsWindowSize" property by which you can control the size of the iframe and content within. 

**Additional context**
See info here https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~additionalInformation

**Comment by serhii-tkachenko** [comment]
Hello @twm-jamieb.
Thanks for raising this issue. It looks good to me to add this feature 👍

**Comment by serhii-tkachenko** [comment]
Also thanks for raising the PR for this proposal. I will ask BigCommerce Checkout team to review your PR on their side and then we will merge it.
