### ISSUE TITLE
Braintree - Error processing network-tokenized cards through GooglePay when 3D Secure enabled

### ISSUE THREAD

**Issue by twm-jamieb** [bigcommerce/checkout-sdk-js#2750]
**Describe the bug**
When using GooglePay through Braintree and 3D Secure is enabled, if the card in Google Pay is network tokenized then 3D Secure will fail with the message "the data passed in 'verifyCard' did not pass validation checks". The error in the request relates to the 3D Secure lookup and the error maps to Braintree sdk error - 94503 (Cannot 3D Secure a non-credit card payment instrument).

This is caused by the fact that 3D Secure lookup is not required and cannot be performed on network tokenized cards, as per Braintree's documentation - https://developer.paypal.com/braintree/docs/guides/3d-secure/advanced-options/javascript/v3/#verify-google-pay-card-using-3ds

**To Reproduce**
I haven't been able to add a tokenized card to GooglePay when using Braintree sandbox so it can only be reproduced in production
1. Add a new card to your GooglePay account via the **Google Wallet** app. (Cards added via pay.google.com are not network tokenized). You can verify that a card is network tokenized by the "bin" returned from GooglePay API and passed to the payment initializationData not being equal to the first 6 digits of the credit card used.
2. Try to pay using that card with GooglePay via Braintree with 3D Secure enabled
3. You will see the error "the data passed in 'verifyCard' did not pass validation checks"

**Expected behavior**
3D Secure is skipped as it's not required for network tokenized cards (like with ApplePay) and the payment goes through successfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/0b5f9c79-471d-4646-8792-4db1e6e1c3d4)

![image](https://github.com/user-attachments/assets/9e4f5197-b1b2-45ee-93b3-759e5b86e3cc)

<img width="340" alt="image" src="https://github.com/user-attachments/assets/8facf5d8-eada-42fc-9ccc-eac09c708cdf">

**Comment by animesh1987** [comment]
@serhii-tkachenko can we please have a look at this issue.
