### ISSUE TITLE
CDN for umd build

### ISSUE THREAD

**Issue by napalm272** [bigcommerce/checkout-sdk-js#383]
Hi, is `checkout-sdk.umd.js` on a CDN some where? I would like to use it in a script tag, but I don't want to host it myself.

**Comment by davidchin** [comment]
Hi @napalm272, we don't have that yet. But we plan to have a CDN version some time in the future.

**Comment by fthobe** [comment]
Hi @napalm272 , I know it’s not perfect but you can upload it via WebDAV to 

/content/newsubfolder/

In that way it would not add a DNS call and pretty much resolve the issue. It’s not as fast as CDN but still very quick given that the file size is manageable.

**Comment by capsula4** [comment]
This is now supported, please check https://github.com/bigcommerce/checkout-sdk-js#using-cdn-url
