### ISSUE TITLE
Feature request - better types for coupon errors

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#386]
### Problem 
Currently, when user try to apply coupon `applyCoupon` method may give generic error like `Error: Coupon code '1DAA7FDCB4F9925' is not eligible for this checkout`.

This can indicate lots of things:
 - User may need to add more items to cart because coupon has minimum cart amount limit
 - User may need to add different items to cart because coupon is specific to certain product
 - etc..

If coupon is disabled, we get errors like `Error: Coupon code '7AD4E90C18D1DCC' is invalid`.  There is no way for SDK client to distinguish this vs error above without parsing error message.

### Request
Define type for coupon error. Error type should have a type enum so SDK client can distinguish various errors and can provide proper message to users.

**Comment by davidchin** [comment]
This is a great idea. We could return more granular error types so it's easier for clients to handle errors.

**Comment by capsula4** [comment]
This is a good initiative. Most of our errors only return a description message. We have created an internal ticket to return more structured data so the client have more options about how to handle the error.

**Comment by capsula4** [comment]
We have started to roll out a feature where failed coupons should have a `code` attribute in the payload where you should be able to identify the issue without parsing the text.
