### ISSUE TITLE
Documentation request - difference between cart.discountAmount and cart.discounts.discountedAmount

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#387]
More detailed documentation will help SDK users a lot :)

For instance, one may think `cart.discountAmount` is a sum of `cart.discounts.discountedAmount`, but in reality these two seems to be completely independent value (!)
My current understanding is `cart.discountAmount` is a cart-level discount while `cart.discounts` is a user-entered coupons. 

Can these information explicitly added to https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/cart.md ?
![screen shot 2018-08-25 at 7 39 01 pm](https://user-images.githubusercontent.com/980077/44624292-11668d00-a89f-11e8-8b91-a826af93e171.png)

**Comment by davidchin** [comment]
Yes, the current documentation definitely has areas that could be improved upon (i.e.: descriptions for returning objects). We'll look into it.

**Comment by bc-0dp** [comment]
Closing this, as discussion can take place on the PR.
