### ISSUE TITLE
loadCheckout throws exception instead of returning error as getLoadCheckoutError

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#393]
Following code seems ok but in reality it throws exception at runtime. 

```
  const result = await sdk.loadCheckout();
  if (result.errors.getLoadCheckoutError()) {
     console.log('error');
  }
```

When I call this logic in cart page, if user completes the checkout and then come back to cart page, exception with message `Checkout Id <id> does not exist` (`<id>` is alphanumeric sequence)

I think loadCheckout should always resolve regardless of success or not, and if it ends up in error, return error details with `result.errors.getLoadCheckoutError()`

**Comment by davidchin** [comment]
Hi @daisy1754, we throw this error intentionally. This is because sometimes you might want to chain this method call with another method call. If we don't throw an error, you'll need to write a guard statement to determine whether or not you should make the second method call. That might be cumbersome for people to work with.

**Comment by daisy1754** [comment]
Thanks for response @davidchin . My argument is about inconsistency of way the library returning errors. I think both returning error object and throwing exception are valid patterns, but having both is a bit painful.
Given erros object has `getLoadCheckoutError` method, caller will need to check `getLoadCheckoutError()` as well. So, you'll end up writing code like:

```
let result;
try {
  result = await sdk.loadCheckout();
} catch (e) {
  handleException(e);
  return;
}
if (result.errors.getLoadCheckoutError()) {
  handleError(result.errors.getLoadCheckoutError());
  return;
}
// do meaningful thing here
```

I'll be happy if I can do either
```
let result;
try {
  result = await sdk.loadCheckout();
} catch (e) {
  handleException(e);
  return;
}
// do meaningful thing here. result.data is guaranteed to have meaningful thing here.
```
or 

```
const result = await sdk.loadCheckout(); // this never throws
if (result.errors.getLoadCheckoutError()) {
  handleError(result.errors.getLoadCheckoutError());
  return;
}
// do meaningful thing here. result.data is guaranteed to have meaningful thing here.
```

**Comment by davidchin** [comment]
Oh I see what you mean. If something goes wrong, the error that gets thrown by the method (`loadCheckout`) and the error that gets returned by the getter (`getLoadCheckoutError`) should be the same. So you don't really have to check both. The error getter is useful if you choose to subscribe to changes in another part of the app. i.e.:

```js
checkout.subscribe(({ errors }) => {
    // Render `errors.getLoadCheckoutError()`
});
```

On the other hand, the rejected promise is useful if you need to chain promise calls.

```js
const { data } = await checkout.loadCheckout();

await doSomethingElse(data.getCheckout());
```

So depending on your use case, you might want to choose to handle errors in one way over another.

**Comment by davidchin** [comment]
Sorry I probably didn't explain myself properly last time. What I meant is (referring to your example):

```ts
try {
    await sdk.loadCheckout();
} catch (error) {
    const { errors } = sdk.getState();

    // True, because the error that gets thrown by the method (loadCheckout) and the 
    // error that gets returned by the getter (getLoadCheckoutError) are the same.
    console.log(error === errors.getLoadCheckoutError());
}
```

So you shouldn't really have to check twice, if you know what I mean.

**Comment by davidchin** [comment]
I'm going to close this issue. Please let me know if you have any more questions.

**Comment by agrohs** [comment]
I am working with the checkout sdk example (react) and had to add in the ability to delete items from the cart during checkout (which we have working successfully using the old CartUtils - may switch over to the v3 cart API, but for now using cartutils), but can't figure out for the life of me where to catch this error inside of checkout.jsx?

It gets thrown after the last item in the cart is deleted as it seems the cart itself doesn't exist at that point - which is fine, but I want to be able to detect the error and redirect to the home page or cart page. Any help/direction would be appreciated!
