### ISSUE TITLE
Shipping option undefined error on order submit

### ISSUE THREAD

**Issue by arizvifolio3** [bigcommerce/checkout-sdk-js#394]
Dear Support,

We are using BC checkout-sdk-js for one of our client. We setup stencil theme locally and up running with checkout-sdk-js.
While submitting order, getting error **"Shipping option undefined"**.
Find the attached screenshot:

![checkout-sdk-issue](https://user-images.githubusercontent.com/38132294/45044167-c57acb80-b088-11e8-9fa0-ae8aa8f78852.PNG)

**Comment by capsula4** [comment]
In order to submit an order, you must have a shipping option selected. Are you able to provide the network call screenshot of the failed request? Ideally send the whole network activity in a HAR file https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366

**Comment by arizvifolio3** [comment]
Thanks for the quick reply. On store portal we are using default enabled shipping method **Free Shipping**. We are sure, things setup correctly because default checkout working fine with same configurations.

**Logged In user case -** Fill all required fields on checkout page **(using checkout-sdk)** while place order getting error **"Shipping option undefined"** but order confirmation email received on my email and in admin portal order created with status **"Awaiting Fulfillment"**. This happen with logged in user.

**Guest user case -** After Fill all required fields on checkout page **(using checkout-sdk)** while place order getting error **"Shipping option undefined"**, no order placed.
   
Find the attached HAR and log with for both cases **guest and login** user.

[checkout-sdk-network-console-log.zip](https://github.com/bigcommerce/checkout-sdk-js/files/2351988/checkout-sdk-network-console-log.zip)

**Comment by arizvifolio3** [comment]
Any update on this? We are in a development phase with short deadline. Hopeful for positive response very soon

Thanks,
Syed Aun

**Comment by capsula4** [comment]
Sorry for the delay in the answer. I have noticed that the error/bug that you are referring to is coming from our [Checkout SDK Example](https://github.com/bigcommerce/checkout-sdk-js-example), not the Checkout SDK itself.

The Checkout SDK Example is not meant to be a fully functioning checkout and was not intended to be used in production. It is just a prototype to provide some guidance on how the SDK should be used, hence there could be some issues.

However, will investigate the issue on the other repo.

**Comment by capsula4** [comment]
Checkout SDK Example fix: https://github.com/bigcommerce/checkout-sdk-js-example/pull/11

**Comment by arizvifolio3** [comment]
Thanks for the quick reply. I will test it. If every thing working fine will close this thread. :)

**Comment by arizvifolio3** [comment]
Thanks its working fine. :)
