### ISSUE TITLE
No endpoint for creating a customer, or for the link to the customer creation page

### ISSUE THREAD

**Issue by horyd** [bigcommerce/checkout-sdk-js#419]
You can sign a customer in, sign them out, proceed as guest, but can't sign a new customer up within the flow of the checkout.

If that's not possible then it would be great to have the URL to the Register page available within the checkout service so I can create a link to the page from my React FE.

**Comment by icatalina** [comment]
closed by mistake

**Comment by capsula4** [comment]
Thanks for the feedback. We won't be supporting account creation any time soon via Checkout SDK, but exposing an URL sounds good enough for now. We will look into it.

**Comment by horyd** [comment]
Awesome, thanks @capsula4!

**Comment by capsula4** [comment]
The link for account creation has been added to the StoreConfig.

```js
checkoutService.getState().data.getConfig().links.createAccountLink
```

I will close this for now as we don't have plans any time soon to add customer management as part of the Checkout SDK.

**Comment by flyingL123** [comment]
@capsula4 the links in this object always refer back to the store's live domain, not the domain on which the store is running. In other words, if you're developing with stencil, running on localhost, you will still get links to your live store. It would be great if these links contained the correct domain.
