### ISSUE TITLE
address.address2 and address.countryCode can be null

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#420]
https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/address/address.ts

Type says it's not optional but in the real world we're seeing null is passed to these fields. 

Can SDK make sure always set empty string or update type definition?

**Comment by daisy1754** [comment]
OK created https://github.com/bigcommerce/checkout-sdk-js/pull/434

**Comment by capsula4** [comment]
API has been fixed to always return a string.
