### ISSUE TITLE
How can we let users subscribe newsletters?

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#424]
Is it possible to let user subscribe newsletters via checkout SDK?

Looks like SDK expose config (below) but there is no method to update user's preference. Can such method be added?

```
export interface ShopperConfig {
    defaultNewsletterSignup: boolean;
    passwordRequirements: PasswordRequirements;
    showNewsletterSignup: boolean;
}
```

**Comment by capsula4** [comment]
At the moment we don't have a public API for it, hence why we have not provided functionality for it yet via the SDK.

**Comment by richardgill** [comment]
Thanks @capsula4 any word on when this might happen? You seem to have almost everything covered, shame to be missing this one piece.

**Comment by davidchin** [comment]
Thanks for your feedback and suggestion. I've added an enhancement label to this issue so we can keep track of it.

**Comment by ryan-timothy-albert** [comment]
Hi BigCommerce team is there any update on this.

**Comment by fthobe** [comment]
@capsula4 Hi Luis, is there any update on this?

**Comment by mpatin** [comment]
@capsula4 - is there any update on supporting this?

**Comment by fresh5447** [comment]
I was looking through the docs to see if there was any other API (v2, v3, storefront) we could use to update/set the customers' newsletter signup. Wasn't able to find anything promising.

Anyone know if there is *any* API to accomplish this?

**Comment by fthobe** [comment]
Hi @fresh5447 , the problem

**Comment by amie-wilt** [comment]
Any update on this?

**Comment by pwillia7** [comment]
Subscribers can be added via the Subscribers API, which should allow you to integrate newsletter functionality into a custom checkout. 
https://developer.bigcommerce.com/api-reference/store-management/subscribers/reference/customers-subscribers/createsubscriber

**Comment by capsula4** [comment]
we are in the process of releasing a storefront API for this, and this is the PR that adds this functionality in the SDK https://github.com/bigcommerce/checkout-sdk-js/pull/827
