### ISSUE TITLE
Issue with credit card payments

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/checkout-sdk-js#430]
Hi, I have had success with testing the payment gateway, but when trying anything else (Braintree,Authorize) I keep getting this same error https://screencast.com/t/aLrMObkKGtY. I am pretty positive im doing this according to the docs, can you give any insight on this error? https://screencast.com/t/YrYxkMkMs

**Comment by capsula4** [comment]
Code looks okay to me, but it's hard to see what could be failing. Maybe try to debug, find where it's blowing up, and see what's causing the exception?

We use the SDK in production and those payment methods work. Do you have a HAR files includes network requests? API responses might help us track down the issue.

**Comment by PeteyRev** [comment]
@capsula4 thanks for your quick reply - I viewed the api requests from the HAR file - it is a little confusing to me since it seems like the posting of the order is fine, as well as the get request for the completed order data:
![2018-10-12_1028](https://user-images.githubusercontent.com/5169882/46878778-bb778580-ce09-11e8-9d6b-1c330e77ed9a.png)

 I have double checked and the order is not posting to the store, when i refresh the page the order is still in the cart. One thing I did notice was the post data from showing a blank customer message:
![00000270](https://user-images.githubusercontent.com/5169882/46878674-7e12f800-ce09-11e8-91ce-c5b4d9be5726.png)

I am not exactly sure why this is showing as I have not added any place for a customer message, and I couldnt find it being required in the docs anywhere

**Comment by PeteyRev** [comment]
@capsula4 dont want to be that guy, but I am still struggling with this. I even used this react sdk example you provided into my own project and am still getting a error - I realize this isnt a production ready version but it still should still work right?

**Comment by capsula4** [comment]
@PeteyRev I'm really sorry I wasn't able to get back to you, this slipped through my things to do. The Checkout SDK React Example is just a quick example of how to use the SDK and might have some issues with specific payment providers.

Back to your original question, the order seems to be created successfully. Most orders are creating as pending as the payment still needs to be manually processed through the control panel. The funds are usually just captured.

The error you are seeing is hard to debug without having the actual code. I would try to use Chrome debugger and trace the error and see what's the part that is actually blowing up. Seems like an array is expected but null is returned.

**Comment by PeteyRev** [comment]
@capsula4 The example sdk doesn't work at all - not relative to payment methods. Does anyone have an actual live example or a working checkout? I have yet to find any one using this.

**Comment by agrohs** [comment]
Yes, we have it up and running. The documentation/steps to set up have been less than ideal but we were able to get it working.

ADAM GROHS.
PARTNER/CO-FOUNDER
646.244.4501

Particular.
the innovation agency of tomorrow, today

www.uniquelyparticular.com

**Comment by PeteyRev** [comment]
@agrohs Hi Adam - agreed on the docs - any insight on the pain points im having?

**Comment by icatalina** [comment]
Hi @PeteyRev!

Do you have a bundle or a store you can share with us to try to debug your issue? You can also try to configure your build to pickup the soucemaps from the sdk, it might give us some clues.

**Comment by PeteyRev** [comment]
@icatalina[ Here is the repo ](https://github.com/PeteyRev/bc-vue-checkout) Right now its a pretty stripped down version not using the vuex store, just trying to get this to work on a very low level. I rebuilt today and now I am getting this issue https://screencast.com/t/ke7FlX1y. This happens when I am going through the checkout process, however if I refresh the page and submit the order it will work.

**Comment by PeteyRev** [comment]
Actually, I was able to get it working after all. . Using the `service` as a vuex store prop was not working, and now Im performing all my logic within the my main app component, and the cards are working now

**Comment by cherupil** [comment]
I'm experiencing this same issue, I've done as @PeteyRev has suggested and changed `service` from a Vuex store property to data on the main app component, the results are the no different. Maybe @PeteyRev can provide more insight as to the solution for this or @davidchin given that this has the 'investigate' tag on it now. I'm able to successfully use the test payment gateway with the same code, but braintree credit cards and braintree paypal result in this exact error. The orders are created as 'Pending'.

<img width="799" alt="Screen Shot 2019-06-30 at 11 44 46 PM" src="https://user-images.githubusercontent.com/8054842/60409355-4b747f80-9b91-11e9-89b0-b6b6f0f04a63.png">
<img width="1322" alt="Screen Shot 2019-06-30 at 11 45 04 PM" src="https://user-images.githubusercontent.com/8054842/60409356-4b747f80-9b91-11e9-89d6-94c8c05898a7.png">
<img width="680" alt="Screen Shot 2019-06-30 at 11 45 52 PM" src="https://user-images.githubusercontent.com/8054842/60409357-4b747f80-9b91-11e9-8970-0904c879d1a4.png">

**Comment by icatalina** [comment]
Hi @cherupil!

Could you please share the code, a store with the failing checkout or upload an HAR capture of your issue (https://toolbox.googleapps.com/apps/har_analyzer/)?

From the network screenshot it looks like the payment request is not happening, but it is really hard to tell only from the screenshots.

Regards,
Ignacio

**Comment by icatalina** [comment]
Also, is this happening while using the `stencil-cli`? or after deploying your code to production?

**Comment by cherupil** [comment]
Hi @icatalina 

I'll start with a HAR file and then work on getting you the theme code. This also occurs with both the stencil-cli and after deploying.
[hanna-instruments.mybigcommerce.com.har.zip](https://github.com/bigcommerce/checkout-sdk-js/files/3377557/hanna-instruments.mybigcommerce.com.har.zip)

**Comment by cherupil** [comment]
@icatalina I've just given you access to the private hnna-checkout repository

**Comment by icatalina** [comment]
Looking at your HAR, there seems to be missing a request to the payment's endpoint. I'll have a look at the code.

**Comment by icatalina** [comment]
After having a play with the code I've figured out the issue. Apparently `Vue` will append keys to the objects it deals with:

<img src="https://user-images.githubusercontent.com/4542735/61024140-056cb680-a3f0-11e9-865e-51d6eac86005.png" width="252"/>

We are expecting all the keys in that object to be arrays of `LineItems`, but the last key (`__ob__`) isn't.

I'm not experienced with Vue, but a quick solution might be to do a clone of `order.lineItems.physicalItems` before you consume it in your app.

I'm working on a more permanent solution in the SDK, I'll update this ticket when it is fixed.
