### ISSUE TITLE
Braintree payment methods incorrect

### ISSUE THREAD

**Issue by richardgill** [bigcommerce/checkout-sdk-js#431]
I'm using sandbox Braintree account (I had to call support to get them to enable it).

Here are the important settings: 

<img width="705" alt="screen shot 2018-10-11 at 08 21 34" src="https://user-images.githubusercontent.com/6640874/46787153-ca3d3a00-cd2e-11e8-9c3f-e54c9316237a.png">
Here is the response from the API:

<img width="1252" alt="screen shot 2018-10-11 at 08 23 34" src="https://user-images.githubusercontent.com/6640874/46787245-07093100-cd2f-11e8-9737-8ffb676f0d04.png">

No logo is returned for Paypal but is returned for the credit card form. This is the opposite from the stock optimized checkout and seems wrong.

**Comment by jonathandelefortrie** [comment]
Hello @richardgill , thanks for opening that issue. It happens that the ```logoUrl``` should not be public, this is a mistake and it will be fixed shortly. The different logos used on the checkout page are just internal assets. I recommend you use your own images as it might be easier for you to maintain.

**Comment by richardgill** [comment]
Ok yep - that sounds good 👍
