### ISSUE TITLE
Multiple Braintree PayPal checkout buttons not appearing correctly on cart page

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#432]
There seems to be an issue with the Braintree PayPal integration. I have noticed recently that only one of the three PayPal buttons on our checkout are appearing. Please see below:

The cart page has 3 locations where the button is supposed to appear.

Location 1: Mobile-only top location
Location 2: Desktop-only top location
Location 3: Mobile and Desktop bottom location

The buttons used to appear in all three locations as expected, but recently I've noticed that only Location 1 is appearing, and the other two locations do not show a button.

This is troublesome for us since we need the button to appear in multiple places. For example, here is the mobile layout, which works correctly since the mobile-only top location is the first one in the markup. The PayPal button appears correctly underneath the AmazonPay button:

<img width="378" alt="paypal_location1" src="https://user-images.githubusercontent.com/2486712/46834010-2d06f380-cd78-11e8-8f34-9ebb4aff8fcd.png">

However, there should also be a PayPal button in Location 3 underneath the Amazon button, but as you can see, it does not appear:

<img width="378" alt="paypal_location3" src="https://user-images.githubusercontent.com/2486712/46834796-64769f80-cd7a-11e8-8ff7-47ce5483ed7d.png">

Additionally, on desktop, no PayPal buttons appear since desktop uses Location 2 and Location 3:

<img width="1190" alt="paypal_location2and3" src="https://user-images.githubusercontent.com/2486712/46834043-44de7780-cd78-11e8-9d17-97546f6c1e14.png">

Location 2 and 3 both contain the code to show the button, but they never appear:

<img width="1341" alt="paypal_code" src="https://user-images.githubusercontent.com/2486712/46834096-79523380-cd78-11e8-861f-cf9dbc581814.png">

To reproduce, go to https://www.storeyourboard.com/skateboard-deck-display-floating-mount/ and click "Add to Cart". The issue appears on the cart page as long as an item is in the cart.

In other words, the checkout buttons only appear when an item is in your cart. So make sure there is an item in your cart. Then anytime you visit the cart page, you will see the issue.

I can also see that 3 calls to get the checkout button are being made, but only one is being rendered. [I started by reporting the issue to PayPal](https://github.com/paypal/paypal-checkout/issues/890), but I'm now pretty sure the issue is on the BigCommerce side since the issue does not occur in their testing environment.

Again, this used to work correctly, so I'm assuming it has something to do with the new checkout SDK. Can someone help figure this out?

**Comment by capsula4** [comment]
Thanks for the feedback! This is a known issue and it's on our list of things to be fixed.

**Comment by flyingL123** [comment]
Thanks for the response @capsula4 - is there any sort of timeline on this? It's effectively making PayPal unavailable to our customers on desktop. Not ideal.

**Comment by davidchin** [comment]
We're looking to address this issue this week or the next. We'll keep you updated. I apologise for the delay.

**Comment by flyingL123** [comment]
Hey @davidchin any update on getting this fixed?

**Comment by davidchin** [comment]
I just want to give you an update. We have an engineer working on the issue at the moment.

**Comment by capsula4** [comment]
https://github.com/bigcommerce/checkout-sdk-js/pull/443
