### ISSUE TITLE
LineItemOption.value is empty for checkbox modifier option

### ISSUE THREAD

**Issue by daisy1754** [bigcommerce/checkout-sdk-js#493]
1. Create modifier option via API as documented in https://developer.bigcommerce.com/api-docs/catalog/products/modifier-options#modifier_add-modifer
Just in case link changes, API payload is:
```
{
  "type": "checkbox",
  "required": false,
  "config": {
    "default_value": "Yes",
    "checked_by_default": false,
    "checkbox_label": "Check for Donation"
  },
  "display_name": "Add a $5 Donation"
}
```

2. Now go to storefront and add item. Below is console.log of `item.options`. As you can see , value of option (Yes/No) is shown in cart page, but it's not available from SDK.

![bc_sdk_valud_is_empty](https://user-images.githubusercontent.com/980077/49555799-14b5df80-f8b6-11e8-9009-b64741901888.png)

**Comment by bc-0dp** [comment]
Closing this as fixed
