### ISSUE TITLE
Payment Unexpected Error

### ISSUE THREAD

**Issue by ONeill45** [bigcommerce/checkout-sdk-js#512]
I am building a custom checkout using the Checkout SDK React example as a basis. I am now noticing an issue with submitting payments via the Cybersource credit card payment method. Upon submission I am receiving "An unexpected error occurred." Using Google dev tools, I can see the error returned by 
https://payments.bigcommerce.com/api/public/v1/orders/payments is: 

![image](https://user-images.githubusercontent.com/13375042/51127895-a0475800-17f4-11e9-8d86-954dd1f57cce.png)

I cannot figure out why this is happening, the card being used is valid. The payment data upon submission appears as such: 

![image](https://user-images.githubusercontent.com/13375042/51128329-983be800-17f5-11e9-81a4-bec49fee7a02.png)

The payment configuration for Cybersource comes through as:

![image](https://user-images.githubusercontent.com/13375042/51128462-e94bdc00-17f5-11e9-911f-fb376cc1153d.png)

Anyone have any thoughts?

**Comment by davidchin** [comment]
Hi @ONeill45, sorry for the late reply. I believe `ccExpiry.year` field needs to be 4 digits. For example, in your case, the year should be `2020` instead of `20`. I hope it helps :)

**Comment by davidchin** [comment]
I assume the above has addressed your issue. So I'm going to close this ticket. Feel free to re-open it if it hasn't and I'm happy to look at it again. 😄

**Comment by ONeill45** [comment]
Hey @davidchin  thanks for the response! We ended up going with the default Big Commerce provided checkout due to time constrains but I'll circle back and confirm if this solution works.
