### ISSUE TITLE
Missing group name and id in customer object

### ISSUE THREAD

**Issue by emilian** [bigcommerce/checkout-sdk-js#514]
Previously, the older "quote" API included the customer group id and customer group name as part of the customer object. However, the newer checkout endpoint does not include this data.

Is it possible to add these properties back to the customer object returned by the checkout endpoint?

**Comment by bookernath** [comment]
@emilian you might also consider using the [Current Customer API](https://developer.bigcommerce.com/api-docs/customers/current-customer-api) which returns this data.

**Comment by capsula4** [comment]
This has been added in https://github.com/bigcommerce/checkout-sdk-js/pull/703
