### ISSUE TITLE
shouldSaveInstrument does not vault credit card

### ISSUE THREAD

**Issue by ArchangelGabriel** [bigcommerce/checkout-sdk-js#522]
When a customer checks out with a new credit card using braintree as a payment method, configuring paymentData.shouldSaveInstrument to `true` does not vault the credit card.

**Comment by ArchangelGabriel** [comment]
Upon looking at the requests, I see that it's calling a graphql endpoint to tokenize the credit card. Within that request, I see no field related to vaulting the instrument. As compared to a normal express checkout where it made a call to `/v1/orders/payments` with a field `vault_payment_instrument` set to `true`.

**Comment by ArchangelGabriel** [comment]
This is how I submit the order:

```javascript
service.submitOrder({
  methodId: "braintree",
  paymentData: {
    ccNumber: "XXXXXXXXXXXX0597",
    ccExpiry: {
      month: XX,
      year: XX
    },
    ccName: "Name Name",
    ccCvv: "XXX",
    shouldSaveInstrument: true
  },
  useStoreCredit: true,
})
```

**Comment by davidchin** [comment]
Thanks for reporting this issue. I believe there's an issue with the API. We're currently investigating the root cause. :)

**Comment by ArchangelGabriel** [comment]
Changing the following:
1. `ccExpiry.month` from number to string
2. `ccExpiry.month` from number to 4 character string
    
Solved the issue for me.

**Comment by davidchin** [comment]
Thanks @ArchangelGabriel. We'll perhaps add the above information in the documentation, or make some changes in the code so it can accept `year` with 2 digits as well.

**Comment by icatalina** [comment]
Anything you put in those values gets cast as `Number` by `bigpay-client-js`, so it doesn't really matter if we pass a string or a number in here. I think the main issue is having year as 2 digits vs 4 digits. As @davidchin pointed out we could make it take 2 digit years and just add `2000` if needed in `bigpay-client-js`.
