### ISSUE TITLE
How to submit the order with VaultedInstrument when trusted shipping address is false?

### ISSUE THREAD

**Issue by ArchangelGabriel** [bigcommerce/checkout-sdk-js#525]
If I am correct, this is how the payment section of express checkout looks like when `instrument.trustedShippingAddress` is `false`:

![screen shot 2019-02-14 at 2 37 31 pm](https://user-images.githubusercontent.com/5737176/53042527-12dad180-344c-11e9-9144-5d7994d18765.png)

My question is how do I submit the order to account for this case? [VaultedInstrument](https://github.com/bigcommerce/checkout-sdk-js/blob/afca385686906d4cd0f2baf7c3728200fa583ca4/docs/interfaces/vaultedinstrument.md) does not seem to have a field where I can put in a credit card number.

**Comment by ArchangelGabriel** [comment]
Fixed by [v1.18.2 release](https://github.com/bigcommerce/checkout-sdk-js/releases/tag/v1.18.2).

**Comment by davidchin** [comment]
Ah I see, thanks @ArchangelGabriel. Yes `ccNumber` and `ccCvv` fields were missing from the TypeScript interface. They have been added since that version.
