### ISSUE TITLE
deinitializePayment issue with google pay.

### ISSUE THREAD

**Issue by navx2810** [bigcommerce/checkout-sdk-js#526]
Hello, I'm having a problem with Google Pay.

I can initialize google pay and proceed through checkout just fine, but when I try to use deinitializePayment  to select a different payment method, I get an error:

```
vendors~main.js:1 Uncaught (in promise) Error: Unable to proceed because payment method data is unavailable or not properly configured.
    at n._subscribe (vendors~main.js:1)
    at n._trySubscribe (vendors~main.js:1)
    at n.subscribe (vendors~main.js:1)
    at n._subscribe (vendors~main.js:1)
    at n._trySubscribe (vendors~main.js:1)
    at n.subscribe (vendors~main.js:1)
    at t.call (vendors~main.js:1)
    at n.subscribe (vendors~main.js:1)
    at t.call (vendors~main.js:1)
    at n.subscribe (vendors~main.js:1)
```

Once google pay is initialized, how can I remove it so we can choose another payment method again?

Thanks.

**Comment by davidchin** [comment]
Hi @navx2810, thanks for reporting this issue. Can I ask which payment provider are you using with GooglePay (i.e.: Braintree or Stripe)? Also, when you call, `deinitializePayment`, what `methodId` are you passing?

**Comment by navx2810** [comment]
The method ID I'm passing is ```googlepaybraintree``` and I'm using Braintree.

**Comment by navx2810** [comment]
Has there been any progress on this issue?

**Comment by davidchin** [comment]
Hi @navx2810, sorry for not giving you an update earlier. My colleagues and I have been trying to replicate the issue but so far have not been able to. So my suspicion is that `googlepaybraintree` payment method is in fact missing, which is odd because without it you wouldn't be able to display and/or initialise the payment method. Can you try one thing for me? Can you try calling `checkoutService.getState().getPaymentMethod('googlepaybraintree')` and let me know if you get anything back?

**Comment by navx2810** [comment]
Thanks @davidchin. I was able to get back the [payment method](https://imgur.com/3dqxwpz) object.

The first log contains payment methods returned by the SDK, and the second is after calling getPaymentMethod.

**Comment by davidchin** [comment]
Hrmm, that's odd. How come the first log returns an array of `PaymentMethod` object and the second log returns a single `PaymentMethod` object?

**Comment by navx2810** [comment]
The array comes from ```getPaymentMethods()```, the second object was the ```PaymentMethod``` returned from ```getPaymentMethod("googlepaybraintree")```.

**Comment by navx2810** [comment]
@davidchin, is there a different method I should use to set and destroy the payments for this?

**Comment by davidchin** [comment]
Hi @navx2810, there isn't a different method for you to call. I tried to replicate the error you posted again. I could only do if if I pass in a wrong argument to `deinitializePayment`. i.e.: `deinitializePayment('googlepaybraintree')` instead of `deinitializePayment({ methodId: 'googlepaybraintree' })`. Can you confirm if you're passing in the right argument?

**Comment by navx2810** [comment]
Hi @davidchin. Yes I can confirm that I'm sending it over correctly.
```await service.deinitializePayment({ methodId: "googlepaybraintree" });```.

**Comment by navx2810** [comment]
@davidchin, is it possible to provide a working sample of code for initializing + deinitializing google pay correctly?

**Comment by icatalina** [comment]
Hey @navx2810, we have a centralized (de)initialization method for all payment providers, here's an excerpt:

Initialize:
```js
function initializePayment(methodId, gatewayId, options) {
    return checkoutService.initializePayment({
        methodId,
        gatewayId,
        ...options,
    });
}
```

Deinitialize:
```js
function deinitializePayment(methodId, gatewayId) {
    return checkoutService.deinitializePayment({ methodId, gatewayId });
}
```

This is the call we use for googlebraintree:

```js
paymentProvidersService.deinitializePayment(paymentProvider.method);
```

The error you are seeing comes from these lines:
https://github.com/bigcommerce/checkout-sdk-js/blob/fa085a44cea9c502dce14d605b78efb660990ea2/src/payment/strategies/googlepay/googlepay-payment-strategy.ts#L141-L145

Can you check which requests you get when the error happens, and what's the error (if there's any) in them?

Thanks :)

**Comment by icatalina** [comment]
I just checked and we seem to be using `googlepay` as method:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/4542735/55595812-4a4dd500-5791-11e9-97ba-9f52436cea8d.png">

It comes from `paymentMethod.method`. If your paymentMethod contains a gateway make sure u pass it as well.

**Comment by navx2810** [comment]
@icatalina, thanks for your response.

We are sending the gatewayId and methodId through, but it is not deinitializing.

Here is the current payment information from the service after we signin with google pay.

![image](https://user-images.githubusercontent.com/3950980/56149048-a8d93700-5f79-11e9-8a8f-2d153e56e922.png)

The code I'm using to deinitialize that payment is this

```
await service.deinitializePayment({ methodId: "googlepaybraintree", gatewayId: null });
```

We're not getting any network data errors, but there's no change in state after that deinitialize and we can not longer get our other payment methods as options, google pay is the only one in the list.

Here are our payment methods before signing into google pay.

![image](https://user-images.githubusercontent.com/3950980/56149469-a88d6b80-5f7a-11e9-8b82-26039d3fff29.png)

Here are the ones available to us after signing into google pay.

![image](https://user-images.githubusercontent.com/3950980/56149537-c65ad080-5f7a-11e9-9304-f79eb8cd25a0.png)

At this point, I'm not sure how to proceed with properly removing google pay after a custom logs into it. Is this a one-way action, once they sign in, there's no way to get to another payment method?

Thanks.

**Comment by icatalina** [comment]
Hi @navx2810!

As I mentioned on my previous comment, `methodId` should be `googlepay` not `googlepaybraintree`:

![image](https://user-images.githubusercontent.com/4542735/56179786-62074200-604a-11e9-9623-df53680f8ebe.png)

**Comment by navx2810** [comment]
@icatalina, I tried that but I did not get an error nor did it deinitialize. Let me see if I can articulate the problem better.

I enter my details and get down to the portion of the code where I initialize a payment method.
Before doing so, here is the state of my application.
![image](https://user-images.githubusercontent.com/3950980/56688742-74672880-66a7-11e9-8134-fe10a261c340.png)

I then initialize google pay successfully.
![image](https://user-images.githubusercontent.com/3950980/56688778-8ba61600-66a7-11e9-8b93-0dcbad060214.png)

At this point, two things happen. Let me explain the first.

If I click on another payment method, it does not initialize itself, so I tried running this line of code.
```
if (this.paymentIsReady) {
    console.log("deinitializing googlepay");
    try {
        await service.deinitializePayment({ methodId: 'googlepay', gatewayId: null });
    } catch (err) {
        console.error(err)
    }
}
``` 

This does not fail, and does not deinitializing the payment. It is still google.

The second issue is, if I reload the page. I ONLY get google pay as a payment method, and I still can't deinitialize.
![image](https://user-images.githubusercontent.com/3950980/56688943-f3f4f780-66a7-11e9-98eb-e43b6797312d.png)

At this state, if the user wants to switch back to credit card, what am I supposed to do in the code to get this to happen? I can't see any payment methods, so I can't show them additional options. I assumed I had to deinitialize the payment method in order to reset the payment state and get the correct payment methods.

Could you advise me on how I can accomplish this?
Thanks.

**Comment by navx2810** [comment]
@icatalina, is there any documentation or instructions I'm missing on how to implement this?

**Comment by navx2810** [comment]
Unfortunately, this issue has not been solved.

But after talking with BigCommerce Partner support, they suggested a solution listed here:
https://github.com/bigcommerce/checkout-sdk-js/issues/549

The solution is to use ```service.signOutCustomer``` instead of ```service.deinitializePayment```. After a page reload, the checkout resets back to the first user step (but keeps the items in the cart).

**Comment by JoannaMakary** [comment]
This seems to still be an issue, have tried using both methods (deinitializePayment and signOutCustomer) but the user's details are still stored in the Google Pay gateway and will not show the other payment methods unless they are to open a new browser where their details are not saved.
