### ISSUE TITLE
Phone number on checkout 

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/checkout-sdk-js#530]
@bookernath referenced in #514 the usage of the customer Current Customer API. Trying to query additional fields of the customer it seems nevertheless impossible to get the phone number.

**Comment by icatalina** [comment]
Not sure what your use case is. Phone numbers are not part of the customer object but rather the addresses in the address book. Are you looking at getting that information within the storefront? or on a server to server scenario?

**Comment by fthobe** [comment]
Hi @icatalina thank you for your reply. We ship good with a high ticket value, ergo we frequently rely on proxies to identify our customers. Especially in southern and central europe the cell phone number is frequently used for that. In addition the phone number allows you to implement two step verification via text message with client side jscript. All there ;)

**Comment by icatalina** [comment]
That's fine, but the phone number, unless you add it as a custom field for the customer, is not a field that belongs in the customer resource.
