### ISSUE TITLE
how to apply store credit

### ISSUE THREAD

**Issue by AllenDiao** [bigcommerce/checkout-sdk-js#538]
Hi, first thanks for helping me out.
When reading docs, my understanding is that I can switch to use store credit when submitOrder
this.service.submitOrder({ payment,  useStoreCredit: true, })

My questions is, once customer logged in, how can I apply storecredit to cart/order? is this need to be done manually? Thank you

**Comment by davidchin** [comment]
Hi @AllenDiao, thank you for your question. If a shopper is signed in and has store credit available, their store credit will get applied if `useStoreCredit` is set to `true` when calling `submitOrder`. Otherwise, if the flag is not passed or set to false, their store credit will not be applied to the order. Does this answer your question?

**Comment by AllenDiao** [comment]
@davidchin . Thanks for the quick answer.  Yes, submitOrder with useStoreCredit: true works. However, this wont update cart/summary which is a bit confusing. 

What I have done is conditionally minus storecredit in Cart/order summary panel. and by doing this, I also add a bit logic for "ispaymentrequired" during the payment rendering. This is now working fine.

My question is about whether there is a service we can call like "useStoreCredit" or "applyStoreCredit"? Fully understand storecredit is a payment, maybe a checkbox in payment section so that user can easily select to use the credit and cart will update accordingly. Similar as how coupon code works  It will be nice to have this feature :) 

All good for now. 
one more suggestion is fully customized order confirmation page :) 
Thank you

**Comment by AllenDiao** [comment]
Hi, As an update. Figured out a way to customize confirmation page :)
Sorry for all frontend questions, new to bigcommerce and not quite familiar with what is possible. Thanks again for the great work

**Comment by davidchin** [comment]
Thanks for the clarification and suggestion. Yes you're correct, currently we don't have a way to apply store credit as a separate step (similar to the way we apply gift certificate or coupon). And I agree, it would be a nice feature to have. I've added `enhancement` label to this issue so we can keep track of it. :)

**Comment by capsula4** [comment]
We have added a new method for applying store credit as a separate step.

[CheckoutService#applyStoreCredit](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#applystorecredit)
