### ISSUE TITLE
Instructions on how to add the option to save a payment method

### ISSUE THREAD

**Issue by TheCrawlingChaos** [bigcommerce/checkout-sdk-js#553]
I am using the checkout sdk in conjunction with the reactjs checkout-app. 

I intend to provide user with option to persist the cc for future purchases when they check out. Already on the BC plus plan. 

I would like some pointers on how that can be accomplished. 

I see there is a loadPaymentMethods, but I don't see a way to "update" or "persist' a payment method. 

Presumably it would be somewhere in the submitOrder method. I do see that the submitOrder method has a "RequestOptions" field, which can be a "PaymentRequestOptions". Presumably I can pass some flag there saying I want to persist this payment method. But doc doesn't mention how that can be done. 

Please provide pointer on how to do this. Thanks.

**Comment by tatiana-perry** [comment]
You can do this as part of the [submit order](https://github.com/bigcommerce/checkout-sdk-js#submit-order) step. Instead the payment method should be creditcard.
Use the [shouldSaveInstrument](https://github.com/bigcommerce/checkout-sdk-js/blob/decf28d8eb17504bfbe2b4a7227c94c14f3d963a/docs/interfaces/creditcardinstrument.md#shouldsaveinstrument) field to save the credit card to store the card.

To make it available for a shopper later, use [loadPaymentMethods](https://github.com/bigcommerce/checkout-sdk-js/blob/2ee02662156517279111252ae91c04ef9e5a9259/docs/classes/checkoutservice.md#loadpaymentmethods).  Our readme has the steps on how to [submit a payment and an order](https://github.com/bigcommerce/checkout-sdk-js#submit-payment-and-order).

Note: Cards can only be vaulted for signed in customers.

**Comment by TheCrawlingChaos** [comment]
So, it appears when I set shouldSaveInstrument to true, then submitOrder, the order goes through. However, when I try to visit (using a fake customer account) /account.php?action=payment_methods, I get a "Server Error Something went wrong... Please try again later." message. 

I am not sure what's broken here. Since I have zero visibility into BC internal systems, would need some help on this.

**Comment by adaamcollins** [comment]
@TheCrawlingChaos, it’s a bug in the BC API, if you pass the year as 2 character string, it accepts the order but it causes a problem with the vaulted card, you just have to pass the year as a 4 character string on the submitOrder method (eg: instead of 22, pass 2022).

See the issue related to this here for full info: #522

**Comment by TheCrawlingChaos** [comment]
I am able to save the cc, thanks @adaamcollins ! 

Just one last question related to the use of vaulted instruments in the "submitOrder" call. 

It seems that if the saved instrument's "trustedShippingAddress" is set to _false_, then I must ask for ccNumber and ccCvv again, and pass those in the _paymentData_ object, in order for the API to accept the checkout.  Otherwise, it would give me a 400. FWIW I am using stripe. I want to confirm that this is the way the API is supposed to be used.

**Comment by adaamcollins** [comment]
@TheCrawlingChaos - yeah that’s exactly how it works. If trusted = false, you must supply the full card number again as well as CVV.

Unfortunately I only found this out whilst putting together a checkout myself, it’s not documented anywhere as far as I can tell.

I’m not sure on the implications of the Stripe CVV setting being false, as it’s always been a requirement for us to ask the user to provide this with each order.

**Comment by tatiana-perry** [comment]
> @tatiana-perry I think you meant the [loadInstruments](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#loadinstruments) method, rather than the **loadPaymentMethods** - in order to show the saved cards to the shopper on return.
> 
> > You can do this as part of the [submit order](https://github.com/bigcommerce/checkout-sdk-js#submit-order) step. Set the payment method to the payment provider available on the store.
> > Use the [shouldSaveInstrument](https://github.com/bigcommerce/checkout-sdk-js/blob/decf28d8eb17504bfbe2b4a7227c94c14f3d963a/docs/interfaces/creditcardinstrument.md#shouldsaveinstrument) field to save the credit card.
> > To make it available for a shopper later, use [**loadPaymentMethods**](https://github.com/bigcommerce/checkout-sdk-js/blob/2ee02662156517279111252ae91c04ef9e5a9259/docs/classes/checkoutservice.md#loadpaymentmethods). Our readme has the steps on how to [submit a payment and an order](https://github.com/bigcommerce/checkout-sdk-js#submit-payment-and-order).
> > Notes: Cards can only be stored for signed in customers.
> > Not all payment providers offer stored cards. See our [Payments API](https://developer.bigcommerce.com/api-docs/payments/payments-api-overview#payments_processing-payment) documentation.
> > Stored cards must be enabled in the [store settings](https://support.bigcommerce.com/s/article/Enabling-Stored-Credit-Cards) as well.

Thanks for clarifying that!
