### ISSUE TITLE
AMAZON PAY CONTAINER ID

### ISSUE THREAD

**Issue by bg2492** [bigcommerce/checkout-sdk-js#562]
I am trying to implement amazon pay on bigcommerce checkout custom SDK, but in the documentation it states I need an amazon pay container ID. I Have contacted amazon and they said they dont have an amazon pay container ID. can someone help

**Comment by karen-white** [comment]
Hey @bg2492 ,
Container ID will be the ID of a DOM element where Amazon should insert its widget into the page.

`<div id="walletWidget"></div>`

```
await service.initializePayment({
    methodId: 'amazon',
    amazon: {
        container: 'walletWidget',
    },
});
```

https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/amazonpaypaymentinitializeoptions.md#amazonpaypaymentinitializeoptions

Hope that helps!

**Comment by bg2492** [comment]
Hi,
I am actually getting the error below when I try to use amazon pay and Klarna.

theme-bundle.main.js:54 Uncaught (in promise) Error: Unable to initialize payment because "options.amazon" argument is not provided.
    at t.initialize (theme-bundle.main.js:54)
    at t._subscribe (theme-bundle.main.js:54)
    at t._trySubscribe (theme-bundle.main.js:16)
    at t.subscribe (theme-bundle.main.js:16)
    at t._subscribe (theme-bundle.main.js:40)
    at t._trySubscribe (theme-bundle.main.js:16)
    at t.subscribe (theme-bundle.main.js:16)
    at t.call (theme-bundle.main.js:16)
    at t.subscribe (theme-bundle.main.js:16)
    at t.call (theme-bundle.main.js:54)

**Comment by karen-white** [comment]
Hi @bg2492 , could you share what you're passing for the initialization request when you get that error? Also with Klarna, you'll need to pass a gateway ID in addition to the container ID:

https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/paymentinitializeoptions.md#gatewayid

**Comment by capsula4** [comment]
@bg2492, according to what you shared, it seems like you are missing `{ amazon: { ...params } }` argument as options when initialising the payment.

I will close the issue for now but feel free to reopen if you are still encountering problems.

**Comment by bg2492** [comment]
I am getting this now.

<Payment
    errors={ errors.getSubmitOrderError() }
    methods={ data.getPaymentMethods() }
    onClick={ (name, gateway) => {
            if(name == 'amazon'){
                this.service.initializePayment({
                    methodId: name,
                    amazon: {
                        ...params,
                        container: 'walletWidgetDiv',
                        onReady:this.amazonOnReady,
                        onPaymentSelect:this.amazonOnPaymentSelect,
                        onError:this.amazonOnError
                    }
                })
            }
            else if(name == 'klarna'){
                this.service.initializePayment({
                    methodId: name,
                    klarna: {
                        container: 'walletWidget2',
                        onLoad:this.klarnaOnLoad
                    }
                })
            }
            else{
                this.service.initializePayment({ methodId: name, gatewayId: gateway })
            }
        }
    }
    onChange={ (payment) => this.setState({ payment }) } />
