### ISSUE TITLE
Google analytics enhanced transaction tracking not working with hosted payment 

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/checkout-sdk-js#606]
**Expected Behavior**
When using hosted payment solutions such as Adyen the customer should be redirected to checkout so that the finalize payment method can be invoked to add additional jscript (eg Google Analytics Conversion Tracking) can be fired. 

**Current behavior** 
As payments.bigcommerce.com handles redirect to the order confirmation page for hosted payment gateways skips the return to checkout, finalize order can’t be invoked therefor the transaction can’t be send to google analytics.

**Comment by davidchin** [comment]
Hi @fthobe, yes, you're correct. For some hosted payment methods, shoppers won't be redirected back to checkout after providing their payment details. Instead, they will be redirected to the order confirmation page if their payment is successful. Perhaps you can fire the tracking event on the order confirmation page instead?

**Comment by fthobe** [comment]
Hi Davidchin , the order confirmation page has very limited abilities regarding the information provided on the page and the customization possibilities are very limited. The problem could be resolved if it would be technically feasible to either redirect after payment to the checkout again (given that the system already has the information) or to allow custom payment methods. Given that our industry is flagged as high risk by Stripe and Braintree (refurbished smartphones are high risk, who would have thought of that), both providers are not an option.

**Comment by fthobe** [comment]
@davidchin Hi David, I completed and improved and spelling and writing on this issue. Could you flag it as enhancement and keep a tab on this issue.

**Comment by davidchin** [comment]
Hi @fthobe, I believe you can customise the order confirmation page as you do with the checkout page. Also, you should be able to retrieve the full details of the recently completed order of a shopper. It is the information we use to trigger the order complete event to Google Analytics in Optimised One-Page Checkout (the default checkout of BigCommerce). Perhaps you have additional information you want to send? Can you tell me what information that's missing?

**Comment by fthobe** [comment]
Hi @davidchin , we proceeded with implementing Google Analytics on the order confirmation page. Maybe that would be a good place in general given the hosted gateway issue. Do you think that should be documented somewhere?

**Comment by icatalina** [comment]
Hi @fthobe!

Since you seem to have resolved your issue, do you mind if I close this ticket?

Regards

**Comment by fthobe** [comment]
Hi @icatalina , in general not, but maybe you could find 5 minutes to document the issue in the readme. I believe it would really help other people. Fabian

**Comment by icatalina** [comment]
I didn't meant to close it... it was a genuine question, hehe

This issue should serve as documentation, but It'll try to add some notes in the markdown files.

**Comment by fthobe** [comment]
Hi @icatalina , how about this: 
## Limitations
* It is not possible to fire additional jscript events after the transaction when paying on hosted payment pages such as Adyen as payment confirmation is handled by payments.bigcommerce.com, therefore the order confirmation page must be used to to send the transaction to Google Analytics.
