### ISSUE TITLE
Determine whether a credit card or debit card is being used?

### ISSUE THREAD

**Issue by Ky1e** [bigcommerce/checkout-sdk-js#614]
With surcharging/convenience fee gaining traction we are looking to see if we can both:
a) Determine whether a credit card or debit card is being used. 
b) If a debit card is being used to checkout then remove the predetermined surcharge amount.

I searched through the SDK and I couldn't find any endpoints that determine debit vs credit.

**Comment by icatalina** [comment]
Hi @Ky1e!

There's no functionality in the SDK to determine whether the shopper has provided a credit or a debit card. 

You could use some 3rd party service like binlist for this: https://binlist.net/

Kind Regards

**Comment by capsula4** [comment]
We are not intending to support this feature any time soon. Closing for now.
