### ISSUE TITLE
Default Shipping Option

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/checkout-sdk-js#624]
Currently there's no documentation for the setting default shipping option in the BigCommerce backend: 
- how do we handle configuration of the default shipping option as described here
[Link to documentation](https://support.bigcommerce.com/s/article/Optimized-Single-Page-Checkout)
![Image of Optimized Checkout Documentation](https://www.ricomprostaging.it/content/temp/Screenshot%202019-07-08%20at%2014.10.57.png)

@catokx

**Comment by icatalina** [comment]
Hi @fthobe !

That configuration gets surfaced as an `isRecommended` flag on the list of available shipping options. It is a responsibility of the UI to do the selection.

https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/shippingoption.md#isrecommended

**Comment by fthobe** [comment]
Hi Ignacio, thank you, we figured it out in the meantime. I really appreciate your help though ;)
