### ISSUE TITLE
Customer state after sign in is stale.

### ISSUE THREAD

**Issue by fresh5447** [bigcommerce/checkout-sdk-js#627]
I have gone about trying this in many different ways, but here is the gist of it.

I sign in the customer, then log the state of the customer:

```
const state = yield service.signInCustomer({ email, password });
console.log('CUST AFTER SIGN IN', state.data.getCustomer());
```

However, the data is always coming back as a guest: `{id: 0, isGuest: true, email: "", firstName: "", lastName: "", …}`

It doesn't seem to be a timing issue, as I wait a minute then call `state.data.getCustomer()` and still the same results.

I know the sign in is a success because I see the updated customer profile after I do a hard page reload.

This is driving me bonkers, please halp!

**Comment by icatalina** [comment]
Can you please check what the response is? The data you get with `.getCustomer()` should match the `customer` key in the most recent response.

![image](https://user-images.githubusercontent.com/4542735/61011586-7d21ed80-a3be-11e9-971d-e669d13a2cda.png)

**Comment by fresh5447** [comment]
Hey @icatalina  - I will check but I am just realizing this is a duplicate unresovled issue: https://github.com/bigcommerce/checkout-sdk-js/issues/422

And yes my issue is in local dev.

**Comment by fresh5447** [comment]
@icatalina - It looks like the `reponse` from `POST` to `ttp://localhost:3000/internalapi/v1/checkout/customer` has the correct customer data.
