### ISSUE TITLE
Allow creating customers in Checkout flow

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/checkout-sdk-js#634]
N.B. This issue has been crossposted to Cornerstone Theme Git as it's not clear to me which one would be the appropriate.

### Introduction
Our store has implemented user registration via a proprietary middleware handling user registration right inside the checkout. In this way we have increased conversion rate by 400%. I would like to bring this issue up as it seems one of the most underrated missing features of BigCommerce and concerns the checkout in particular.

### Current Feature Set
Right now to register a user during checkout following steps have to be taken: 
1. Add a product to cart 
2. Proceed to Checkout
3. Click Sign-In 
4. Click Register User
5. Leave Checkout to user registration page
6. Fill out 11 form fields containing the full address
7. save the new account and return to the home page
8. return to checkout by finding the basket 
9. complete billing address
10. Pay

### Problems with this process
1. Confusing for customers
2. Less qualified data for the merchant due to more guest-accounts than neccessary(guest account vs customer account)
3. pushing customers to guest checkout instead of user registration providing especially in GDPR countries many legal issues (a registered user gives a legal justification to store data, while guest user data can only be stored as long as necessary for processing the order, as long as they don't opt in into privacy and general terms such as a regular user)
4. guest users support less features in BC (nobody ever explained why)
5. users with intention to register eventually have a higher abandoning rate due to more complex process with confusing changes to UI and UX

To give a clear comparison you can find below our proprietary true one page checkout (screenshot) compared to the steps necessary and BigCommerce right now to execute a registration when purchasing a good. 

### Solution
The BigCommerce API v2 and v3 support customer registration. They should be embedded in the Checkout SDK enabling a truly conversion optimised checkout improving revenue for merchants. See the picture below for an example of a one-page solution as we have implemented it with a custom middleware vs a video registration of todays default one page optimized checkout when registering a customer. 

![Screenshot 2019-07-16 at 14 15 27](https://user-images.githubusercontent.com/579379/61294087-5b1cd680-a7d5-11e9-8709-82b90b8555a9.png)
[![](http://img.youtube.com/vi/EVKnudTFNe8/0.jpg)](http://www.youtube.com/watch?v=EVKnudTFNe8 "Optimized One-Page Checkout")

**Comment by capsula4** [comment]
Hi Fab, 

Currently BC supports guest customer flow, which does not require a user to register in order to make a purchase. Creating an account should not be a blocker for completing the checkout funnel. 

We currently have server-to-server APIs for creating customers, but we still have to build a Storefront Customer API.

We will update the ticket when we have news.

**Comment by fthobe** [comment]
@capsula4 Hey Luis, any updates on this one?

**Comment by flyingL123** [comment]
@capsula4 any update?

**Comment by fthobe** [comment]
Hey, version [https://github.com/bigcommerce/checkout-sdk-js/releases/tag/v1.285.2](Version 1.285.2) finally did it.

**Comment by fthobe** [comment]
For added information: https://github.com/bigcommerce/checkout-sdk-js/commit/1546208336baa1b20f07417ab758e085299f452b

**Comment by fthobe** [comment]
@capsula4 You have no idea how much this meant to me <3 https://github.com/bigcommerce/checkout-sdk-js/commit/1546208336baa1b20f07417ab758e085299f452b
