### ISSUE TITLE
Braintree PayPal payment method always sends customers first stored address.

### ISSUE THREAD

**Issue by aaronr222** [bigcommerce/checkout-sdk-js#640]
When using braintree paypal payment method it appears the customers first stored address is always sent to the paypal payment as seen below. 

https://github.com/bigcommerce/checkout-sdk-js/blob/986366cfce46b738eccb54a54d08cf19bfc5a1a6/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts#L86

If the user has multiple addresses stored would it be possible to send any of the addresses stored as opposed to always sending the first.

**Comment by aaronr222** [comment]
Reopened this issue because I'd like to get some feedback on it.

Here is a more detailed description:

Using Braintree PayPal works as expected for a guest checkout. They enter a shipping address via the checkout address form and that address is sent to PayPal checkout correctly. 

However, when a user is logged in to the store and has multiple delivery addresses stored on their account the SDK always instantiates the Braintree PayPal button with their first stored address, despite if they entered a different address or selected one of their other stored addresses. This then sends the first address to the PayPal checkout.

Correct me if I'm wrong but I still believe this to be an issue with this line https://github.com/bigcommerce/checkout-sdk-js/blob/986366cfce46b738eccb54a54d08cf19bfc5a1a6/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts#L86
as this is hardcoding the button to use the customers address at index 0 despite if they have multiple stored addresses and selected another address.

**Comment by capsula4** [comment]
Hi @aaronr222, this sounds like a legit request. We could potentially have an optional parameter where you pass a specific address for initializing the button, or `null` / `false` to have an initial empty address and have an experience similar to the guest checkout flow. 

@davidchin thoughts?
