### ISSUE TITLE
getShippingCountries not working

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/checkout-sdk-js#644]
I am not seeing this method in the docs, but I see it in the source code - unless I am not using this correctly - How are we to get the available shipping/billing countries? I am calling this after I am calling `state.data.getShippingAddressFields()`

**Comment by fresh5447** [comment]
This is how I load shipping countries
```
  const service = createCheckoutService();
  const shippingCountries = await service.loadShippingCountries();
```

And then the data comes in like so:
```
shippingCountries.data._countries._countries.data
```

**Comment by PeteyRev** [comment]
@fresh5447 thanks, just figured that out today as well.
