### ISSUE TITLE
Versioning strategy

### ISSUE THREAD

**Issue by lukeconvertdigital** [bigcommerce/checkout-sdk-js#675]
Just wondering if you're using semver for versioning the package? Can we expect minor version releases are backwards compatible?

**Comment by icatalina** [comment]
Hi @lukeconvertdigital !

Yes, we are using `semver`, and yes, they should be backward compatible. You can read a bit more in the contribution guide https://github.com/bigcommerce/checkout-sdk-js/blob/master/CONTRIBUTING.md#release-version

If you found somewhere where this doesn't hold true, feel free to raise an issue and we'll look into it.

Thanks,
Ignacio
