### ISSUE TITLE
Tax and digital products

### ISSUE THREAD

**Issue by kzhang-dsg** [bigcommerce/checkout-sdk-js#682]
When checkout with only digital product in the cart, there are several issues with CheckoutSDK:

1. The updateShippingAddress() call fails with 422 response code:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/15915824/63102960-c1665780-bf41-11e9-8354-5b59c739eeda.png)
This may not be an issue because digital product does not need shipping. But it will impact the tax calculation (see below)
2. We were able to workaround the updateShippingAddress() issue by catching the error. But on the next step of checkout, the tax is not calculated. After clicking the place order, on the order confirmation page, it then shows the tax.
For example, on the checkout page, the item is $10, the tax is $0, and the order total is $10. But when click on place order, on the order confirmation page, the the item is $10, the tax is $1, and the order total is $11, which makes the order total mismatch between checkout page and order confirmation page.

**Comment by bc-0dp** [comment]
@kzhang-dsg was this resolved in the end?

**Comment by animesh1987** [comment]
Going to close this issue.
