### ISSUE TITLE
updateShippingAddress() does not have Custom Items in lineItems payload

### ISSUE THREAD

**Issue by LiHsuanChen** [bigcommerce/checkout-sdk-js#701]
When a custom item is added to cart, it doesn't show up in the lineItems payload when updateShippingAddress() is called. This is causing error when I only have custom items in cart and want to call updateShippingAddress();

**Comment by capsula4** [comment]
Hi Terry, thanks for reporting this bug.

We have created a ticket in our internal board so a backend engineer can take a look at this. We will update the ticket when we have more information.

Greets,
Luis

**Comment by kyle-bolt** [comment]
Is there an update on this request?

**Comment by capsula4** [comment]
Sorry for the delay in tackling this. We thought there was no support to do this from the Storefront API. However this issue only required a fix at the Checkout SDK level. Next time you are welcome to submit a PR yourself!
