### ISSUE TITLE
Paypal / Paypal Credit not firing finalizeOrderIfNeeded

### ISSUE THREAD

**Issue by fresh5447** [bigcommerce/checkout-sdk-js#713]
I am able to trigger a successful redirect to paypal, and then back to the checkout. However, calling `finalizeOrderIfNeeded` upon page load returns:

`OrderFinalizationNotRequiredError: The current order does not need to be finalized at this stage.`

Maybe I am missing a step but I am able to get the hosted payment flow to work for Visa Checkout without any additional calls.

Is there a piece of checkout state I can look at to see if something is missing? Or is there a different way to finalize a PayPal payment?

Looking at a couple pieces of state at this time:
`service.getState().data.getPaymentMethod()`  -> `undefined`

`service.getState().data.getSelectedPaymentMethod()` => `{id: "braintreepaypal", gateway: null, logoUrl: "", method: "paypal", supportedCards: Array(4), …}`

**Comment by capsula4** [comment]
Hey Douglas,

Braintree PayPal doesn't not require the order to be finalized
https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts#L68

The recommended way to execute [CheckoutService#finalizeOrderIfNeeded](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#finalizeorderifneeded) is by catching the `OrderFinalizationNotRequiredError`

```js
try {
    await service.finalizeOrderIfNeeded();

    window.location.assign('/order-confirmation');
} catch (error) {
    if (error.type !== 'order_finalization_not_required') {
        throw error;
    }
}
```

**Comment by fresh5447** [comment]
Thanks @capsula4. Sorry are you saying paypal does not require finalizeOrderIfNeeded?

I am calling this method like you are advising:

```
        finalizeOrder: flow(function* finalizeOrder() {
            yield self.service.loadCheckout();
            try {
                yield self.service.finalizeOrderIfNeeded();
                window.location.assign('/order-confirmation');
            } catch (error) {
                if (error.type !== 'order_finalization_not_required') { // order_finalization_not_required
                    self.logger.error(error);
                }
            }
        }),
```
It works for other methods such as Visa Checkout, however for PayPal it is returning `OrderFinalizationNotRequiredError: The current order does not need to be finalized at this stage`

**Comment by capsula4** [comment]
Hey Douglas, that's correct. Braintree PayPal does not require `finalizeOrderIfNeeded`.

When `finalizeOrderIfNeeded` throws `order_finalization_not_required` then it's safe to ignore and fail silently, like it seems to be happening in this case.

Once you are redirected back to checkout from paypal, you should redirect to `/checkout/order-confirmation`

**Comment by fresh5447** [comment]
Thanks for the feedback @capsula4 

I am now skipping `finalizeOrderIfNeeded`, however the flow still appears to die off after the redirect from Paypayl.

 My understanding is that as soon as they leave paypal the order should then be submitted? However, this is not the case.

My checkout does work for regular payment methods, and Braintree Visa Checkout so I am not sure what I am missing.

There are no errors, it simply just does not submit the order. If I redirect to `/order-confirmation` it redirects back to `/cart.php`.

Here is how I am initializing the paypal button:

```
const initializer = createCheckoutButtonInitializer();

...
                 initializer.initializeButton({
                        methodId: 'braintreepaypal',
                        containerId: 'checkoutButton--paypal',
                        braintreepaypal: {
                            onAuthorizeError: (e) => self.logger.error('braintreepaypal Authorize Error', e),
                            onPaymentError: (e) => self.logger.error('braintreepaypal Payment Error', e),
                        },
                    });
```
Which I believe is according to spec -> https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/braintreepaypalbuttoninitializeoptions.md
