### ISSUE TITLE
Checkout SDK Store Credit Issue. Not applying in the backend.

### ISSUE THREAD

**Issue by missakation** [bigcommerce/checkout-sdk-js#718]
I updated my checkout sdk but I still have a problem with the applyStoreCredit. I have put manually a checkbox, that on change will run applyStoreCredit() function. I am looking at the **state (state.data.getCheckout()),** and I see the outstanding balance has been changed successfully and there is a property isAppliedStoreCredit = true. After that, I have a pay button for which I submit theorder.

```
service.submitOrder({ payment }).then(
                                (res) => {                
                                    console.log(res);
                                }
                            )
```

The order creates successfully, but with no store credit applied in the backend. the returned result even says that store credit has been applied. But when I go to the Bigcommerce admin panel, I see full original price with no store credit deduction.
Can I know what is the issue here ?

**Comment by capsula4** [comment]
Different payment methods work in different ways. What payment method did you experience this issue with?

**Comment by suuuf** [comment]
I see the above issue when using Stripe.

If the storeCredit > grandTotal, so there is no need for paymentData. I call the below service.

`this.service.applyStoreCredit(val);`

I try to submit and the status of the order is "INCOMPLETE" and gets auto cancelled.
