### ISSUE TITLE
Do not depend on deprecated @babel/polyfill

### ISSUE THREAD

**Issue by mikea** [bigcommerce/checkout-sdk-js#791]
@babel/polyfill is deprecated: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

**Comment by bc-0dp** [comment]
@mikea I believe this was resolved, so closing this. Don't hesitate to open a new ticket if you still have concerns about this. ❤️
