### ISSUE TITLE
signOutCustomer providing inconsistent response

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#838]
The promise returned by the [signOutCustomer method](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#signoutcustomer) is supposed to resolve to the current state. When `signOutCustomer()` is called without options, it resolves correctly. However, if it's called for Amazon Pay, like `signOutCustomer({ methodId: 'amazon' })`, the response from the server is empty, so the promise does not resolve to the current state.

This means the UI will not properly update unless the page is fully refreshed. Can this be fixed so that the response from this method can be handled uniformly by my application?

**Comment by bc-0dp** [comment]
Hi @flyingL123 was this resolved?
