### ISSUE TITLE
config links should use current domain, not hardcode the stores live domain

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#841]
If you are developing a custom checkout locally with stencil, your store is likely running on `localhost:3000` or something similar. However, when you access the `state.data.getConfig().links` object, all of the links refer to the store's live domain, rather than localhost. For example, the cart link will be `https://mystore.com/cart.php` rather than `https://localhost:3000/cart.php`.

Can these be updated?

**Comment by bc-0dp** [comment]
Closing with this comment:

I believe that a more appropriate solution would to implement this in your checkout-sdk implementation rather than the SDK itself. Here you would be able to implement a url replace function in your build system when developing locally
