### ISSUE TITLE
Is useStoreCredit needed to submit order?

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#851]
If I have previously called `service.applyStoreCredit(true)`, do I still need to include the `useStoreCredit: true` on the call to `submitOrder`? My testing indicates that I can exclude that property and the server still knows to use the store credit since it was previously applied.

Can you please confirm that's by design and not a bug?

**Comment by capsula4** [comment]
You don't need to supply it using `submitOrder`. That's a legacy design and we should probably mark it as deprecated.
