### ISSUE TITLE
Logging out doesn't set isStoreCreditApplied to false

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#852]
If an existing customer is in a checkout and has applied their store credit, then logs out, the checkout object will still have `isStoreCreditApplied = true`. Shouldn't it be set to false if a customer logs out.

**Comment by capsula4** [comment]
The flag represents the state of a checkout, regardless of store credit being available. If that customer signs-in again, the store credit will be applied.
