### ISSUE TITLE
Error: await is only valid in async functions and async generators

### ISSUE THREAD

**Issue by deepakmchetu** [bigcommerce/checkout-sdk-js#853]
I am using the checkout sdk via the CDN URL: 

https://checkout-sdk.bigcommerce.com/v1/loader.js

I face the issue when I try to load the checkout sdk. Following is my code

```
<script>
    const module = await checkoutKitLoader.load('checkout-sdk');
    const service = module.createCheckoutService();
    const checkoutId = document.querySelector('#order-details-custom').dataset.checkoutId;
    const state = await service.loadCheckout(checkoutId);
</script>
```

It throws a `SyntaxError: await is only valid in async functions and async generators` error in console on the first line.
Note that this runs fine when run directly in the console. Can someone help with whats happening here.

**Comment by capsula4** [comment]
await needs to be used inside an `async` function:

```js
async function(): {
    const module = await checkoutKitLoader.load('checkout-sdk');
    const service = module.createCheckoutService();
    const checkoutId = document.querySelector('#order-details-custom').dataset.checkoutId;
    const state = await service.loadCheckout(checkoutId);
}();
```
