### ISSUE TITLE
Is there a callback that can be used after user signs into PayPal?

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#858]
I am using the CheckoutButtonInitializer to create an "Express Checkout" button using PayPal via Braintree:

![image](https://user-images.githubusercontent.com/2486712/80999461-bd050600-8e12-11ea-90be-06d149b9838f.png)

After the user clicks the PayPal button, they are shown a popup to login to their PayPal account. After they complete that, the popup closes and they are momentarily brought back to my checkout page while the browser reloads. In practice this is not a great experience. Unless you know what you're looking for, there is really no way to know that the browser is reloading. It takes a few seconds and you're just staring at the checkout page wondering what is happening.

Is there any sort of callback that can be used within the [options](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/braintreepaypalbuttoninitializeoptions.md) to know when the user has successfully completed the PayPal login process?

**Comment by capsula4** [comment]
I believe when paypal redirects back to checkout, it's submitting the order/payment in the background. https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts#L64

You could check the store status selectors and show some loading spinner based on  https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/checkoutstorestatusselector.md#issubmittingorder
