### ISSUE TITLE
Storefront Cart API error messages

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#864]
I'm not sure if this is the right place to ask, but why are the error messages with the storefront cart API so unhelpful? For example, if I make a request to add 10 of an item to the cart, but there are only 5 in stock, I get a 400 error saying that the cart can not be found. Meanwhile, if I do this via the `/remote/v1/cart` endpoint instead of the storefront cart api, I get a nice helpful message back saying "We don't have enough in stock on hand for the quantity you selected".

Is the cart API going to be updated to have more helpful error messages? It's difficult to use in production without this improvement.

**Comment by capsula4** [comment]
Thanks for the feedback, we can definitely look into improving our APIs.

Unfortunately, the Checkout SDK is unrelated to Cart management APIs.

The best way for making this happen would be to submit a ticket in our Ideas page https://support.bigcommerce.com/s/ideas. This way, we will be able to better track how many people are encountering the same issues.
