### ISSUE TITLE
embedCheckout and NotEmbeddableError

### ISSUE THREAD

**Issue by Borales** [bigcommerce/checkout-sdk-js#889]
I'm trying to follow this [tutorial](https://developer.bigcommerce.com/api-docs/cart-and-checkout/embedded-checkout/embedded-checkout-tutorial).

But it seems like I'm stuck on Step 4 ("Embed checkout").

Here's my React code (using SDK CDN):

```js
import React, { useState, useEffect } from 'react';
import { Helmet } from 'react-helmet-async';

const Checkout = ({ url }) => {
  useEffect(() => {
    checkoutKitLoader.load('checkout-sdk').then(module => {
      module.embedCheckout({
        containerId: 'checkout',
        url
      });
    });
  }, []);

  return <div id="checkout"></div>;
};

export const EmbeddedCheckout = ({ url }) => {
  const [isLoaded, setIsLoaded] = useState(false);

  return (
    <React.Fragment>
      <Helmet
        onChangeClientState={() => {
          document.querySelector('#bc-checkout-sdk').addEventListener('load', () => {
            setIsLoaded(true);
          });
        }}
      >
        <script src="https://checkout-sdk.bigcommerce.com/v1/loader.js" id="bc-checkout-sdk" />
      </Helmet>
      {isLoaded && <Checkout url={url} />}
    </React.Fragment>
  );
};

```

`({ url })` - `url` in this case is `https://<my-store>.mybigcommerce.com/cart.php?embedded=1&action=loadInCheckout&id=89b9...&token=e4a2afa...`

As a result - I can see a loader spinning for 30-60 seconds and then I get this in the console:

<img width="836" alt="Screenshot 2020-05-26 at 15 20 33" src="https://user-images.githubusercontent.com/1118933/82905714-7c596200-9f64-11ea-845b-7dac6deb2fc9.png">

Am I missing some store configuration or something?

**Comment by Borales** [comment]
Apologies, turned out I had wrong "channel_id" value set on the backend

**Comment by ersurajnegi** [comment]
@Borales i am also facing the same issue. I am not sure which channel id you are referring to?

**Comment by Borales** [comment]
@ersurajnegi a channel ID from the channel manager

**Comment by ersurajnegi** [comment]
Any path or url where do i need to set it?
I already spent 3-4 days on this and unable to integrate this. Not much help while goggling this issue as well
