### ISSUE TITLE
How to integrate checkout sdk js in the base cornerstone theme

### ISSUE THREAD

**Issue by thanicricket** [bigcommerce/checkout-sdk-js#895]
Hi,

We need to use below the checkout sdk js file in our base cornerstone theme.
I have done to implement below the base version checkout sdk in my theme.
https://developer.bigcommerce.com/stencil-docs/customizing-checkout/checkout-sdk-example

But we need updated version how to use in the base cornerstone theme.
https://github.com/bigcommerce/checkout-sdk-js

I have searched related to ts file how to integrate cornerstone theme. But some guys says we cannot able to use ts file inside the theme file.

Could please help how to integrate this version in our base cornerstone theme file. Please share your info.

Checkout sdk js inside we can able to see ts files. Then how to use my theme file. If cornerstone theme ts file. Kindly share your integrated base theme file. Please help!!...... I have suffered this problem.

@capsula4 @icatalina @danieldelcore  @davidchin @vmparra @clopezh @rlopz @PascalZajac @rabinshr @Tharaae

**Comment by capsula4** [comment]
You should be able to do it, but might be easier for you to develop your custom checkout in a separate folder/repository, and the build process might need to be independent from the cornerstone one.

We are about to launch a new functionality that allows the installation of custom checkouts directly via Control Panel. The only thing you need to provide is a URL that points to the JS file of your checkout. You could achieve the same today by loading this JS file in the checkout page of your cornerstone theme.

**Comment by thanicricket** [comment]
@capsula4 Thanks for your help. Right now, I have checked that feature in big commerce. 
My other question,
When we run,
npm install

Then,
npm run dev:server

Then,
We will put the local link "http://127.0.0.1:8080/main.js" on the custom checkout link.

Can we know, When we need to customize the checkout, Each saves we need to build again and re-run?
Because of testing purposes.

Is there is any way of handing this customization? Any npm codes after save to bundle the code? Please advise? How can you build locally?

**Comment by capsula4** [comment]
Please check the following guide for more detailed information: https://developer.bigcommerce.com/stencil-docs/customizing-checkout/installing-custom-checkouts

Thanks,
Luis
