### ISSUE TITLE
Add ESM support for bigcommerce SDK

### ISSUE THREAD

**Issue by roopakv** [bigcommerce/checkout-sdk-js#897]
Considering the SDK uses webpack already adding ESM support should be very simple. Doing this will let anyone who uses the SDK on the frontend perform tree shaking and not have to import the whole library.

It should as simple as bundling with ESM and adding the output to a new directory and adding `"module": "path/to/module/index.js"` in package.json

Happy to make this change but want to make sure this isn't already on the roadmap.

**Comment by davidchin** [comment]
As explained on Slack, we won't add ESM support until we can figure out a reliable way to restrict access to internal modules.
