### ISSUE TITLE
Call to Function() in /dist/checkout-sdk.js prevents compliance with CSP policy. 

### ISSUE THREAD

**Issue by Mikhail-MM** [bigcommerce/checkout-sdk-js#928]
We have a client who is looking to enforce Level 2 CSP compliance on his BigCommerce store.

Adopting a secure CSP policy involves removing all inline script tags. CSP policy also disallows call to the `eval()` and `Function()` calls:
https://developer.chrome.com/extensions/contentSecurityPolicy#JSEval

We need to remove all inline script tags from BigCommerce, and we have done this. However, the main theme bundle fails on a cornerstone theme with checkout-sdk-js as a dependency, due to this line in `@bigcommerce\checkout-sdk\dist\checkout-sdk.js`

This uses a `Function()` call, which is disallowed by CSP - similar to `eval()`
```
Be=Function('\n\'use strict\';\nreturn function loadAffirmJS(apiKey, scriptURL) {\n    var _affirm_config = {\n        public_api_key:  apiKey,\n        script:          scriptURL\n    };\n    (function(l,g,m,e,a,f,b){var d,c=l[m]||{},h=document.createElement(f),n=document.getElementsByTagName(f)[0],k=function(a,b,c){return function(){a[b]._.push([c,arguments])}};c[e]=k(c,e,"set");d=c[e];c[a]={};c[a]._=[];d._=[];c[a][b]=k(c,a,b);a=0;for(b="set add save post open empty reset on off trigger ready setProduct".split(" ");a<b.length;a++)d[b[a]]=k(c,e,b[a]);a=0;for(b=["get","token","url","items"];a<b.length;a++)d[b[a]]=function(){};h.async=!0;h.src=g[f];n.parentNode.insertBefore(h,n);delete g[f];d(g);l[m]=c})(window,_affirm_config,"affirm","checkout","ui","script","ready");\n}')
```

Is there any way around this? Can we extract this? What is this affirm tracker used for?

**Comment by capsula4** [comment]
Currently, there is no way around this. It seems this is required for our integration with Affirm. What you could do in the meantime is, clone the repository and remove affirm related code.

**Comment by Mikhail-MM** [comment]
@capsula4 

Thanks for your response. 

If I understand correctly, we would be making a fork of the checkout-sdk repository and removing 

We're using the checkout-sdk-example React Repo to build our checkout - so I'm guessing we'll actually need to extract this from the distributed/built modules that are being used there - or replace the version of checkout sdk loaded in package.json with our own?

It seems like a challenge, and it seems like it would be difficult to pull in new changes when checkout-sdk gets updates. 

Any chance Affirm could change their integration methods? Using `Function('Arbitrary JS String')` is looked down upon upon as a very insecure method.

**Comment by capsula4** [comment]
Your understanding is correct, I was suggesting forking this repository which it would come with its challenges. 

Unfortunately Affirm is a third-party integration that we support and we can't do much about it at this stage. The way they load their JS files involves using `Function()`. You could perhaps get in touch with them?

If they give you a workaround or if you come up with any other idea, feel free to submit a PR against this repository. I'm afraid we won't have capacity any time soon to address this.

**Comment by Mikhail-MM** [comment]
@capsula4 I've reached out to Affirm Support and brought the issue to their attention, I am hoping that they get back to me with some info.

I was wondering if you had any advice on handling the initial 'fork' idea that you proposed.

We are using the React Example App as the basis of our custom checkout:
https://github.com/bigcommerce/checkout-sdk-js-example

I'm not completely familiar with over-riding npm dependencies.
In the `package.json`, `"@bigcommerce/checkout-sdk": "^1.30.0"` is listed as a dep.

I'm wondering if it would be sufficient to update this line with a reference to our fork instead of the BC package? And uthen pdate any import statements to reference our fork as well?

We would need to get the npm configuration figured out so that our fork would be easily downloadable, but I'm wondering if I've overlooked anything

**Comment by Mikhail-MM** [comment]
Just an update, Affirm told me that they routed this request to their BigCommerce team, so hopefully they do come up with a different way of injecting this code, as it is less-than-secure.

**Comment by Mikhail-MM** [comment]
@capsula4 
I’ve been in touch with the Affirm Support Team - they’ve contacted their internal BigCommerce Integration team. At first, they assured me that the code is secure because even though it uses the `Function(‘js string’)` constructor, it has no chance to receive user input, thus is safe.

I was not satisfied with that as it would still put us in the awkward position of having to manually extract the offending code from the distributed checkout-sdk build.

They’ve just responded with this message today:

Hi Mikhail​,

The engineers looking into this realized that on closer inspection, it appears that the offensive code in question is not actually coming from Affirm itself; our own snippet is being wrapped in the non-CSP-compliant code, which is likely coming from the BigCommerce SDK itself:

Be=Function('\n\'use strict\';\nreturn function loadAffirmJS(apiKey, scriptURL) { << ... actual code snippet provided by Affirm ... >> }')

They are in communications with the team at BigCommerce to resolve this issue. I CC'ed Kevin and Johnny who have been looking into this in case you have any questions.

**Comment by capsula4** [comment]
Thanks @Mikhail-MM  for getting in touch with Affirm.

Although the flagged code lives in the SDK, it was done the way Affirm recommended it in their documentation. I have visited their documentation and it looks they have updated it and recommend a different way of doing it.

We will look into updating our Affirm implementation to use the new secure way.
