### ISSUE TITLE
MissingDataError: Unable to proceed because payment data is unavailable

### ISSUE THREAD

**Issue by ehalca** [bigcommerce/checkout-sdk-js#936]
Getting attached error when trying to checkout with GooglePay through Braintree.

[![enter image description here][1]][1]

Initialize payment method:

 

    const initializePayment = async method => {
        const initializeOptions = {
            googlepaybraintree: {
                walletButton: undefined,
                onError: console.log,
                onPaymentSelect: console.log,
            },
            braintreepaypal: {
                onError:console.log
            }
        };
        const options = initializeOptions[method.id]; 
        try{
            await service.initializePayment({
                methodId: method.id, //value below
                [method.id]: options,
            });
    
        }catch(er){
            console.warn(er)
        }
    }

Submitting:

                     service
                    .submitOrder(data) //value below
                    .then((data) => {
                        window.location.href = new URL(
                            data.data.getConfig().links.orderConfirmationLink
                        ).pathname;
                    })

Where variables are: 

    medhod.id = "googlepaybraintree"

and 

    data = {"payment":{"methodId":"googlepaybraintree","paymentData":{"shouldSaveInstrument":true}}}

Look like I'm missing something, but can't figure it out. 

checkout-sdk version  `1.82.0`

  [1]: https://i.stack.imgur.com/QlqnD.png

**Comment by capsula4** [comment]
Could you attach probably a GIF and/or a HAR file with the network requests? Have you called checkoutService.loadPaymentMethods() ?

**Comment by ehalca** [comment]
> Have you called checkoutService.loadPaymentMethods() ?

Yes.

[Har file](https://drive.google.com/file/d/14zlJL7vLWSzZI5wyiSVlLPY3wDvbALHx/view?usp=sharing)

**Comment by capsula4** [comment]
Apologize for the late reply,

We have recently open-sourced our checkout code. That might help you find if you have missed anything:
https://github.com/bigcommerce/checkout-js/blob/master/src/app/payment/paymentMethod/GooglePayPaymentMethod.tsx

Please feel free to reopen the ticket if you need further help.
