### ISSUE TITLE
PayPal: Unable to open PayPal popup on both desktop and mobile Safari 

### ISSUE THREAD

**Issue by chiaogu** [bigcommerce/checkout-sdk-js#944]
![Aug-03-2020 19-26-47](https://user-images.githubusercontent.com/19208117/89257037-4080ef80-d5da-11ea-84df-d39d2e65b388.gif)

### Description
```javascript
checkoutService.submitOrder({ methodId: 'braintreepaypal' });
```
This function works fine on Chrome, but the promise will be rejected on Safari, and the popup will be blocked.

![image](https://user-images.githubusercontent.com/19208117/89256791-bb95d600-d5d9-11ea-8958-fce25a67bbff.png)

This issue can be reproduced with [bigcommerce/checkout-sdk-js-example](https://github.com/bigcommerce/checkout-sdk-js-example) just like the screen recording above.
Here is my checkout.html:
```html
<div id="checkout-app"></div>
<script src="https://cdn11.bigcommerce.com/s-65xv2m9zph/content/20180927.js"></script>
```

### Steps to Reproduce
1. Open the checkout page on Safari
2. Select PayPal as the payment method
3. Submit Order
- Expected: PayPal popup shows up
- Actual: PayPal popup is blocked

**Comment by chiaogu** [comment]
I thought this was a Braintree SDK problem so I also file an issue there https://github.com/braintree/braintree-web/issues/515.
But according to their comment, it seems the root cause is the timing of invoking `paypal.tokenize`
https://github.com/bigcommerce/checkout-sdk-js/blob/f55b3b75c5ed1ca62666a31835f4868ec9c9619e/src/payment/strategies/braintree/braintree-payment-processor.ts#L50-L74

**Comment by chiaogu** [comment]
I think I found where the problem is. `service.submitOrder` should be executed right after the user interaction if the user chooses PayPal as the payment method.

In `bigcommerce/checkout-sdk-js-example`, `service.submitOrder` is delayed until `service.updateBillingAddress` and `service.continueAsGuest` finish. https://github.com/bigcommerce/checkout-sdk-js-example/blob/df26a2d3b73fea4b1d3663980b1c336cdf721086/src/Checkout/checkout.jsx#L172-L182

This caveat should be mentioned in the document.

**Comment by flyingL123** [comment]
@chiaogu did anybody ever get back to you on this? I am running into the same problem. The PayPal popup gets blocked from opening. On the last step of our custom-built checkout, the user selects PayPal as the payment method, and then clicks "Continue With PayPal":

![image](https://user-images.githubusercontent.com/2486712/93404731-f0dc4780-f858-11ea-9e4b-3b784b382e51.png)

When they click that button, the two main things that happen are:

```

**Comment by flyingL123** [comment]
Here's my workaround, which seems to fix it for now:

```
if (paymentMethod.id === 'braintreepaypal') {
  await Promise.all([
	this.service.submitOrder({ payment }),
	this.service.updateBillingAddress(billingAddress),
  ]);
}
else {
  await this.service.updateBillingAddress(billingAddress);

  await this.service.submitOrder({ payment });
}
```

If PayPal is selected I just make the calls at the same time, which let's the popup open, and continues to save the billing address in the background.

**Comment by chiaogu** [comment]
@flyingL123 No, no one gets back to me.
Your solution seems better than mine. I move `updateBillingAddress` to where I call `initializePayment`, which is the time users select the payment method.

**Comment by ankurbigcomm** [comment]
Apologies for the delayed reply @chiaogu. 

You are right in identifying that the submitOrder request has to be made right after clicking on the submit Order button.. We might need to update the example app to reflect this. 

Meanwhile we have open-sourced our checkout app for you to refer to get an up-to-date version of the implementation.

https://github.com/bigcommerce/checkout-js/blob/7499fea63b04861e8449425fadf0ded54ddb523c/src/app/payment/Payment.tsx#L378
