### ISSUE TITLE
Unable to call service.updateBillingAddress() using custom stateOrProvinceCode

### ISSUE THREAD

**Issue by Mikhail-MM** [bigcommerce/checkout-sdk-js#950]
We've been trying to solve the issue of creating predictable "State or Province" drop-downs for all countries in the BigCommerce checkout.

As far as I am aware, BigCommerce creates a province dropdown for `United States` and `Canada` out-of-the-box, but when other countries are selected, the `<select>` element is replaced with a regular `<input type="text">` input.

We are working with an API that requires a standardized 2-letter Province Code for Billing Addresses - so we have 2 options

1.) Do heavy validation on the Text Input and coax the value until it matches a full province-name that we have on record for that country.

2.) Use data and build out a bunch of province dropdowns for each country.

(For reference, we are using the `checkout-sdk-js-example` repo, the React project.).

We opted for choice 2.

We are encountering a problem, however, where BigCommerce is rejecting billing addresses/address updates in general that do not contain a Province Code from USA/Canada.

Example Data:

```
const fail = {
  "id": "5f2dd288db604",
  "firstName": "Test",
  "lastName": "Test",
  "email": "",
  "company": "CompanyMan2",
  "address1": "512 Main Circle",
  "address2": "",
  "city": "City",
  "shouldSaveAddress": true,
  "stateOrProvince": "Mato Grosso",
  "stateOrProvinceCode": "MT",
  "country": "Brazil",
  "countryCode": "BR",
  "postalCode": "01234",
  "phone": "9123123123",
  "customFields": []
}
```

```
checkoutService.updateBillingAddress(fail)
  .then(data => console.log(data.data.getBillingAddress()))

{
  "id": "5f2dd288db604",
  "firstName": "Test",
  "lastName": "Test",
  "email": "",
  "company": "CompanyMan2",
  "address1": "512 Main Circle",
  "address2": "",
  "city": "CityState",
  "shouldSaveAddress": true,
  "stateOrProvince": "Mato Grosso",
  "stateOrProvinceCode": "", // PROVINCE CODE NOT RETURNED
  "country": "Brazil",
  "countryCode": "BR",
  "postalCode": "01234",
  "phone": "9123123123",
  "customFields": []
}
```

As you can see, `stateOrProvinceCode` is empty.

In contrast, you can see a successful update if we use one of the province codes that existed inside of the `subdivisions` object inside of `data.getBillingCountries()`

Working data:

```
const validUpdate = {
  "id": "5f2dd288db604",
  "firstName": "Test",
  "lastName": "Test",
  "email": "",
  "company": "CompanyMan2",
  "address1": "512 Main Circle",
  "address2": "",
  "city": "CityState",
  "shouldSaveAddress": true,
  "stateOrProvince": "Ontario",
  "stateOrProvinceCode": "ON",
  "country": "Canada",
  "countryCode": "CA",
  "postalCode": "01234",
  "phone": "9123123123",
  "customFields": []
}

checkoutService.updateBillingAddress(validUpdate)
.then(data => console.log(data.data.getBillingAddress()))

{
  "id": "5f2dd288db604",
  "firstName": "Test",
  "lastName": "Test",
  "email": "",
  "company": "CompanyMan2",
  "address1": "512 Donato Circle",
  "address2": "",
  "city": "CityState",
  "shouldSaveAddress": true,
  "stateOrProvince": "Ontario",
  "stateOrProvinceCode": "ON", // PROVINCE CODE RETURNED
  "country": "Canada",
  "countryCode": "CA",
  "postalCode": "01234",
  "phone": "9123123123",
  "customFields": []
}
```

BC seems to be able to validate this `country` & `stateOrProvinceCode` combination, since it DID have it as a subdivison of Canada originally, and calling `checkoutService.updateBillingAddress()` does update the checkout's billing stateOrProvinceCode appropriately.

Any workarounds for this?

**Comment by capsula4** [comment]
> We are encountering a problem, however, where BigCommerce is rejecting billing addresses/address updates in general that do not contain a Province Code from USA/Canada.

Unfortunately, there is no way to get around the validation, at that validations is enforced in many areas in BC and must remain consistent. You must follow BC validation for stateOrProvinceCode. If in BC API a country returns subdivisions, stateOrProvinceCode must be provided. You could decide to add extra validation for countries where BC returns no subdivisions but must adhere to BC validation when subdivisions exist.

**Comment by Mikhail-MM** [comment]
@capsula4 

That makes sense. It seems like we can place values in `stateOrProvince` as required, and this is enough for us - this value seems to be persisted on orders. We just need to send province codes to an external system (Currently looking to have a province dropdown for the United Kingdom).

We have made due by creating the custom province dropdown in React and using the custom `stateOrProvince` values and maintaining an internal hash of province codes that we can map that to, to connect to our external API

**Comment by Mikhail-MM** [comment]
Closing the issue because our work-around is enough for now, but maybe it can help someone
