### ISSUE TITLE
StripeV3: Using separate credit card number, expiry, cvv fields

### ISSUE THREAD

**Issue by joeldentici** [bigcommerce/checkout-sdk-js#954]
When using the "card" method for StripeV3, only the single "flexible card element" is supported by Checkout SDK right now. In addition, it is only possible to use the Checkout SDK to mount one element with the current implementation.

This current interface/implementation is over-encapsulated for no good reason.

[Stripe Elements](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber) supports many different element types that are not supported by the Checkout SDK currently. For example, I linked the "cardNumber" element type.

**Here is the relevant Checkout SDK documentation:**

[CardElementOptions](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/cardelementoptions.md)
[StripeV3PaymentInitializeOptions](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/interfaces/stripev3paymentinitializeoptions.md)

**From the code:**

[Mounting an element](https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3-payment-strategy.ts#L241) uses the `methodId` from the initialize options to select the [StripeElementType](https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3.ts#L748) to use. We are therefore limited to only these elements. Furthermore, it is clear that only one container is supported.

**New Interface:**
I suggest the following new interface to replace the current one. I think it would be unwise to make a breaking change at this point, so I suggested creating a discriminated union / sum type of the old interface and new interface. The old interface can be marked with a deprecated tag if desired. You can discriminate at run time on the existence of the "elements" property.

The new interface is capable of supporting anything the old interface is capable of supporting, so it probably also makes the most sense to transform options belonging to the old interface type to the new interface type upon construction of the payment strategy. The transformed options would then be used to drive the new implementation.

The elements can be checked to work with the supplied "methodId" at runtime when using the new interface (this isn't currently checked, maybe Stripe Elements checks it).

```ts
// much more useful than being forced to pass an "id"
type ElementOrSelector = HTMLElement | string;

// BaseElementOptions is an existing type
interface BaseStripeV3PaymentElement extends BaseElementOptions {
    elementOrSelector: ElementOrSelector;
}

interface StripeV3CardElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'card';

    hidePostalCode?: boolean;

    iconStyle?: IconStyle; // existing type

    value?: string;
}

interface StripeV3CardNumberElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'cardNumber';
}

interface StripeV3CardCVVElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'cardCvc';
}

interface StripeV3CardExpiryElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'cardExpiry';
}

interface StripeV3IdealElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'idealBank';

    value?: string;
}

interface StripeV3IbanElement extends BaseStripeV3PaymentElement {
    stripeElementType: 'iban';

    iconStyle?: IconStyle;

    placeholderCountry?: string;

    supportedCountries?: string[];
}

type StripeV3PaymentElement = (
    StripeV3CardElement |
    StripeV3CardNumberElement |
    StripeV3CardCVVElement |
    StripeV3CardExpiryElement |
    StripeV3IdealElement |
    StripeV3IbanElement
);

interface StripeV3PaymentInitializeOptionsV2 {
    elements: StripeV3PaymentElement[];
}

// rename StripeV3PaymentInitializeOptions to StripeV3PaymentInitializeOptionsV1

type StripeV3PaymentInitializeOptions = StripeV3PaymentInitializeOptionsV1 | StripeV3PaymentInitializeOptionsV2;
```

**Comment by capsula4** [comment]
Thanks for bringing this up. We have forwarded it to our Payment Integrations team.

**Comment by vmparra** [comment]
This issue has been addressed on PR #985

**Comment by joeldentici** [comment]
@vmparra We are trying to integrate this but it seems this line:

https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3-payment-strategy.ts#L270

Checks if a setting is enabled. The instance variable `_useIndividualCardFields` is set to the `useIndividualCardFields` on https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3-payment-strategy.ts#L47 which I copied below.

```
const { initializationData: { stripePublishableKey, stripeConnectedAccount, useIndividualCardFields } } = paymentMethod;
```

This seems to come from the `payments` API response. Looking at that, I can indeed see this option there.

How do we enable this on the store? I don't see any option for the Stripe V3 payment settings to enable/disable this.

**Comment by vmparra** [comment]
> @vmparra We are trying to integrate this but it seems this line:
> 
> https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3-payment-strategy.ts#L270
> 
> Checks if a setting is enabled. The instance variable `_useIndividualCardFields` is set to the `useIndividualCardFields` on https://github.com/bigcommerce/checkout-sdk-js/blob/master/src/payment/strategies/stripev3/stripev3-payment-strategy.ts#L47 which I copied below.
> 
> ```
> const { initializationData: { stripePublishableKey, stripeConnectedAccount, useIndividualCardFields } } = paymentMethod;
> ```
> 
> This seems to come from the `payments` API response. Looking at that, I can indeed see this option there.
> 
> How do we enable this on the store? I don't see any option for the Stripe V3 payment settings to enable/disable this.

Hi @joeldentici, you must reach customer service asking to enable `stripe.v3.card.individualElements` experiment / feature flag.

**Comment by joeldentici** [comment]
@vmparra Thanks! That is what we ended up doing and we were able to start the integration and can confirm the SDK is working as we expected. Thank you for fitting it in to your team's busy schedule!

**Comment by vmparra** [comment]
Good luck on the media presentation! Can't wait to put my hands on one or these consoles.
