### ISSUE TITLE
Order Confirmation Email: Not receiving an email after order completed

### ISSUE THREAD

**Issue by eparkAL** [bigcommerce/checkout-sdk-js#956]
After completing and order and getting to the thank you page the default checkout setup is for an Order Confirmation to be sent out.  When I implemented the checkout SDK, the email is no longer sent out.  The settings are the same as the regular checkout but once the SDK was added to the store they stopped.  

Is this not a default function or did we miss something in the setup?

**Comment by capsula4** [comment]
Our actual checkout process is powered by the Checkout SDK, so this is supported. I'm guessing you must have got something wrong? Are you redirecting to our default Thank You page, or have you implemented your own?

**Comment by Mikhail-MM** [comment]
What order status are you creating your orders with?

**Comment by eparkAL** [comment]
@Mikhail-MM Order status is "Pending" once on the confirmation page.

I am receiving order confirmation emails.  I believe it was due to some adjustments to the address/billing that I was working on.
