### ISSUE TITLE
Loading checkout after cart has line item quantity updated doesn't update

### ISSUE THREAD

**Issue by LordZardeck** [bigcommerce/checkout-sdk-js#971]
Even though I'm calling `service.loadCheckout`, and in the network tab, the quantity is correct, the `data.getCheckout()` doesn't update. It does work if a new _item_ is added, but not if an items quantity is updated. To be clear, outside the checkout sdk, the cart is being updated by another backend. But this shouldn't matter as the checkout SDK receives the correct data, it just doesn't update.

![image](https://user-images.githubusercontent.com/1145989/91522305-8a01e900-e8bf-11ea-8891-bb08ba436b3f.png)

**Comment by LordZardeck** [comment]
To also be clear, the subtotal and everything updates. Just not the line items

**Comment by capsula4** [comment]
We haven't been able to replicate the issue on our end. Our current checkout is powered by the SDK and we cannot see this issue in production. Is this still happening to you? Are you maybe dealing with more than one instances of the Checkout SDK? They do not share state, so if one loads the checkout, the second won't be in sync.
